/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import business.Bus;
import business.BusDirectory;
import business.City;
import business.CityDirectory;
import business.MobilePlan;
import business.MobilePlanDirectory;
import business.MobileServiceProvider;
import business.MobileServiceProviderDirectory;
import business.mysql.MySql;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author nbabu
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        CityDirectory cd = new CityDirectory();
        for(City c : cd.getCityList())
        {
          createBusFromCityCombo.addItem(c.getCityName());
        }
        createBusFromCityCombo.setSelectedItem(null);
        
        MobileServiceProviderDirectory mp = new MobileServiceProviderDirectory();
        for(MobileServiceProvider msp : mp.getMSPList())
        {
          createMSPNameCombo.addItem(msp.getProviderName());
        }
        createMSPNameCombo.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createCityIdField = new javax.swing.JTextField();
        createCityNameField = new javax.swing.JTextField();
        createCityButton = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        updateCityIdField = new javax.swing.JTextField();
        citySearchButton = new javax.swing.JButton();
        cityNameLabel = new javax.swing.JLabel();
        updateCityNameField = new javax.swing.JTextField();
        cityUpdateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cityPositionField = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        deleteCityIdField = new javax.swing.JTextField();
        deleteCityButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        createBusIdField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        createBusNameField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        createBusFromCityCombo = new javax.swing.JComboBox<>();
        createBusToCityCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        createBusStartAtField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        createBusReachAtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        createBusFareField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        createBusTravelDateField = new javax.swing.JTextField();
        createBusButton = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        updateBusIdField = new javax.swing.JTextField();
        updateBusNameLabel = new javax.swing.JLabel();
        updateBusNameField = new javax.swing.JTextField();
        updateBusFromCityLabel = new javax.swing.JLabel();
        updateBusFromCityCombo = new javax.swing.JComboBox<>();
        updateBusToCityLabel = new javax.swing.JLabel();
        updateBusToCityCombo = new javax.swing.JComboBox<>();
        updateBusStartAtLabel = new javax.swing.JLabel();
        updateBusStartAtField = new javax.swing.JTextField();
        updateBusReachAtLabel = new javax.swing.JLabel();
        updateBusReachAtField = new javax.swing.JTextField();
        updateBusFareLabel = new javax.swing.JLabel();
        updateBusFareField = new javax.swing.JTextField();
        updateBusTravelDateLabel = new javax.swing.JLabel();
        updateBusTravelDateField = new javax.swing.JTextField();
        updateBusButton = new javax.swing.JButton();
        updateBusSearchButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        busPositionField = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        deleteBusIdField = new javax.swing.JTextField();
        deleteBusButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        createMSPIdField = new javax.swing.JTextField();
        createMSPNameField = new javax.swing.JTextField();
        createMSPButton = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        updateMSPIdField = new javax.swing.JTextField();
        updateMSPNameLabel = new javax.swing.JLabel();
        updateMSPNameField = new javax.swing.JTextField();
        updateMSPButton = new javax.swing.JButton();
        updateMSPIdSearchButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        MSPPositionField = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        deleteMSPButton = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        deleteMSPIdField = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        createMPIdField = new javax.swing.JTextField();
        createMSPNameCombo = new javax.swing.JComboBox<>();
        createPlanNameField = new javax.swing.JTextField();
        createMPDataField = new javax.swing.JTextField();
        createMPCallsField = new javax.swing.JTextField();
        createMPValidityField = new javax.swing.JTextField();
        createMPPriceField = new javax.swing.JTextField();
        createMPButton = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        updateMPIdSearchButton = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        updateMPIdField = new javax.swing.JTextField();
        updateMSPNameComboLabel = new javax.swing.JLabel();
        updateMSPNameCombo = new javax.swing.JComboBox<>();
        updatePlanNameLabel = new javax.swing.JLabel();
        updatePlanNameField = new javax.swing.JTextField();
        updateMPDataLabel = new javax.swing.JLabel();
        updateMPDataField = new javax.swing.JTextField();
        updateMPCallsLabel = new javax.swing.JLabel();
        updateMPCallsField = new javax.swing.JTextField();
        updateMPValidityLabel = new javax.swing.JLabel();
        updateMPValidityField = new javax.swing.JTextField();
        updateMPPriceLabel = new javax.swing.JLabel();
        updateMPPriceField = new javax.swing.JTextField();
        updateMPButton = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        MPPositionField = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        deleteMPIdField = new javax.swing.JTextField();
        deleteMPButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1000, 1000));

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Create Admin", jPanel15);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("View/Update Admin", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Delete Admin", jPanel10);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("City Id:");
        jPanel11.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 61, -1));

        jLabel2.setText("City Name:");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, -1, -1));
        jPanel11.add(createCityIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 130, -1));
        jPanel11.add(createCityNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 130, -1));

        createCityButton.setText("Create");
        createCityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCityButtonActionPerformed(evt);
            }
        });
        jPanel11.add(createCityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 230, -1));

        jTabbedPane3.addTab("Create City", jPanel11);

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("City Id:");
        jPanel16.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));
        jPanel16.add(updateCityIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 110, -1));

        citySearchButton.setText("Search");
        citySearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citySearchButtonActionPerformed(evt);
            }
        });
        jPanel16.add(citySearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));

        cityNameLabel.setText("City Name:");
        jPanel16.add(cityNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));
        cityNameLabel.setVisible(false);
        jPanel16.add(updateCityNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 110, -1));
        updateCityNameField.setVisible(false);

        cityUpdateButton.setText("Update");
        cityUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityUpdateButtonActionPerformed(evt);
            }
        });
        jPanel16.add(cityUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 190, -1));
        cityUpdateButton.setVisible(false);

        jLabel4.setText("Position:");
        jPanel16.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        cityPositionField.setEnabled(false);
        jPanel16.add(cityPositionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 110, -1));

        jTabbedPane3.addTab("View/Update City", jPanel16);

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("City Id:");
        jPanel17.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));
        jPanel17.add(deleteCityIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 130, -1));

        deleteCityButton.setText("Delete");
        deleteCityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCityButtonActionPerformed(evt);
            }
        });
        jPanel17.add(deleteCityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 220, -1));

        jTabbedPane3.addTab("Delete City", jPanel17);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("System Admin", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Banking Admin", jPanel2);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Bus Id:");
        jPanel12.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));
        jPanel12.add(createBusIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 120, -1));

        jLabel7.setText("Bus Name:");
        jPanel12.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
        jPanel12.add(createBusNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, -1));

        jLabel8.setText("From city:");
        jPanel12.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jLabel9.setText("To city:");
        jPanel12.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        createBusFromCityCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                createBusFromCityComboItemStateChanged(evt);
            }
        });
        jPanel12.add(createBusFromCityCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, -1));

        jPanel12.add(createBusToCityCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, -1));

        jLabel10.setText("Start At:");
        jPanel12.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));
        jPanel12.add(createBusStartAtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, -1));

        jLabel11.setText("Reach At:");
        jPanel12.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));
        jPanel12.add(createBusReachAtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 120, -1));

        jLabel12.setText("Fare:");
        jPanel12.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));
        jPanel12.add(createBusFareField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, -1));

        jLabel13.setText("Travel date:");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));
        jPanel12.add(createBusTravelDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 120, -1));

        createBusButton.setText("Create");
        createBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBusButtonActionPerformed(evt);
            }
        });
        jPanel12.add(createBusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 210, -1));

        jTabbedPane2.addTab("Create Buses", jPanel12);

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Bus Id:");
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));
        jPanel13.add(updateBusIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 120, -1));

        updateBusNameLabel.setText("Bus Name:");
        jPanel13.add(updateBusNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));
        updateBusNameLabel.setVisible(false);
        jPanel13.add(updateBusNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 120, -1));
        updateBusNameField.setVisible(false);

        updateBusFromCityLabel.setText("From city:");
        jPanel13.add(updateBusFromCityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));
        updateBusFromCityLabel.setVisible(false);

        updateBusFromCityCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                updateBusFromCityComboItemStateChanged(evt);
            }
        });
        jPanel13.add(updateBusFromCityCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 120, -1));
        updateBusFromCityCombo.setVisible(false);

        updateBusToCityLabel.setText("To city:");
        jPanel13.add(updateBusToCityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));
        updateBusToCityLabel.setVisible(false);

        jPanel13.add(updateBusToCityCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 120, -1));
        updateBusToCityCombo.setVisible(false);

        updateBusStartAtLabel.setText("Start At:");
        jPanel13.add(updateBusStartAtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));
        updateBusStartAtLabel.setVisible(false);
        jPanel13.add(updateBusStartAtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 120, -1));
        updateBusStartAtField.setVisible(false);

        updateBusReachAtLabel.setText("Reach At:");
        jPanel13.add(updateBusReachAtLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, -1, -1));
        updateBusReachAtLabel.setVisible(false);
        jPanel13.add(updateBusReachAtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 120, -1));
        updateBusReachAtField.setVisible(false);

        updateBusFareLabel.setText("Fare:");
        jPanel13.add(updateBusFareLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));
        updateBusFareLabel.setVisible(false);
        jPanel13.add(updateBusFareField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 120, -1));
        updateBusFareField.setVisible(false);

        updateBusTravelDateLabel.setText("Travel date:");
        jPanel13.add(updateBusTravelDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));
        updateBusTravelDateLabel.setVisible(false);
        jPanel13.add(updateBusTravelDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, 120, -1));
        updateBusTravelDateField.setVisible(false);

        updateBusButton.setText("Update");
        updateBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBusButtonActionPerformed(evt);
            }
        });
        jPanel13.add(updateBusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 210, -1));
        updateBusButton.setVisible(false);

        updateBusSearchButton.setText("Search");
        updateBusSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBusSearchButtonActionPerformed(evt);
            }
        });
        jPanel13.add(updateBusSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, -1, -1));

        jLabel16.setText("Position:");
        jPanel13.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        busPositionField.setEnabled(false);
        jPanel13.add(busPositionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 120, -1));

        jTabbedPane2.addTab("View/Update Buses", jPanel13);

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Bus Id:");
        jPanel14.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 137, -1, -1));
        jPanel14.add(deleteBusIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 130, -1));

        deleteBusButton.setText("Delete");
        deleteBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBusButtonActionPerformed(evt);
            }
        });
        jPanel14.add(deleteBusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 200, -1));

        jTabbedPane2.addTab("Delete Buses", jPanel14);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Bus Admin", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Train Admin", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("MSP Id:");
        jPanel18.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel18.setText("MSP Name:");
        jPanel18.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));
        jPanel18.add(createMSPIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 120, -1));
        jPanel18.add(createMSPNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 120, -1));

        createMSPButton.setText("Create");
        createMSPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMSPButtonActionPerformed(evt);
            }
        });
        jPanel18.add(createMSPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 230, -1));

        jTabbedPane4.addTab("Create MSP", jPanel18);

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("MSP Id:");
        jPanel19.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));
        jPanel19.add(updateMSPIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 120, -1));

        updateMSPNameLabel.setText("MSP Name:");
        jPanel19.add(updateMSPNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));
        updateMSPNameLabel.setVisible(false);
        jPanel19.add(updateMSPNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 120, -1));
        updateMSPNameField.setVisible(false);

        updateMSPButton.setText("Update");
        updateMSPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMSPButtonActionPerformed(evt);
            }
        });
        jPanel19.add(updateMSPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 230, -1));
        updateMSPButton.setVisible(false);

        updateMSPIdSearchButton.setText("Search");
        updateMSPIdSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMSPIdSearchButtonActionPerformed(evt);
            }
        });
        jPanel19.add(updateMSPIdSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel28.setText("Position:");
        jPanel19.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        MSPPositionField.setEnabled(false);
        jPanel19.add(MSPPositionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 120, -1));

        jTabbedPane4.addTab("View/Update MSP", jPanel19);

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteMSPButton.setText("Delete");
        deleteMSPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMSPButtonActionPerformed(evt);
            }
        });
        jPanel20.add(deleteMSPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 230, -1));

        jLabel30.setText("MSP Id:");
        jPanel20.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));
        jPanel20.add(deleteMSPIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 120, -1));

        jTabbedPane4.addTab("Delete MSP", jPanel20);

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setText("MP Id:");
        jPanel21.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel20.setText("MSP Name:");
        jPanel21.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        jLabel21.setText("Plan Name:");
        jPanel21.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jLabel22.setText("Data:");
        jPanel21.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel23.setText("Calls");
        jPanel21.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel24.setText("Validity:");
        jPanel21.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel25.setText("Price:");
        jPanel21.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));
        jPanel21.add(createMPIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 110, -1));

        jPanel21.add(createMSPNameCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 110, -1));
        jPanel21.add(createPlanNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 110, -1));
        jPanel21.add(createMPDataField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 110, -1));
        jPanel21.add(createMPCallsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 110, -1));
        jPanel21.add(createMPValidityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 110, -1));
        jPanel21.add(createMPPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, 110, -1));

        createMPButton.setText("Create");
        createMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMPButtonActionPerformed(evt);
            }
        });
        jPanel21.add(createMPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 230, -1));

        jTabbedPane4.addTab("Create Mobile Plan", jPanel21);

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateMPIdSearchButton.setText("Search");
        updateMPIdSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMPIdSearchButtonActionPerformed(evt);
            }
        });
        jPanel22.add(updateMPIdSearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jLabel26.setText("MP Id:");
        jPanel22.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));
        jPanel22.add(updateMPIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 110, -1));

        updateMSPNameComboLabel.setText("MSP Name:");
        jPanel22.add(updateMSPNameComboLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        updateMSPNameComboLabel.setVisible(false);

        jPanel22.add(updateMSPNameCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 110, -1));
        updateMSPNameCombo.setVisible(false);

        updatePlanNameLabel.setText("Plan Name:");
        jPanel22.add(updatePlanNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, -1, -1));
        updatePlanNameLabel.setVisible(false);
        jPanel22.add(updatePlanNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, -1));
        updatePlanNameField.setVisible(false);

        updateMPDataLabel.setText("Data:");
        jPanel22.add(updateMPDataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));
        updateMPDataLabel.setVisible(false);
        jPanel22.add(updateMPDataField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 110, -1));
        updateMPDataField.setVisible(false);

        updateMPCallsLabel.setText("Calls");
        jPanel22.add(updateMPCallsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
        updateMPCallsLabel.setVisible(false);
        jPanel22.add(updateMPCallsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 110, -1));
        updateMPCallsField.setVisible(false);

        updateMPValidityLabel.setText("Validity:");
        jPanel22.add(updateMPValidityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));
        updateMPValidityLabel.setVisible(false);
        jPanel22.add(updateMPValidityField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 110, -1));
        updateMPValidityField.setVisible(false);

        updateMPPriceLabel.setText("Price:");
        jPanel22.add(updateMPPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));
        updateMPPriceLabel.setVisible(false);
        jPanel22.add(updateMPPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 110, -1));
        updateMPPriceField.setVisible(false);

        updateMPButton.setText("Update");
        updateMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMPButtonActionPerformed(evt);
            }
        });
        jPanel22.add(updateMPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 200, -1));
        updateMPButton.setVisible(false);

        jLabel29.setText("Position:");
        jPanel22.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        MPPositionField.setEnabled(false);
        jPanel22.add(MPPositionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 110, -1));

        jTabbedPane4.addTab("View/Update Mobile Plan", jPanel22);

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setText("MP Id:");
        jPanel23.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));
        jPanel23.add(deleteMPIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 110, -1));

        deleteMPButton.setText("Delete");
        deleteMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMPButtonActionPerformed(evt);
            }
        });
        jPanel23.add(deleteMPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 230, -1));

        jTabbedPane4.addTab("Delete Mobile Plan", jPanel23);

        jPanel5.add(jTabbedPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 870));

        jTabbedPane1.addTab("Recharge Admin", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Utilities Admin", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Events Admin", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Movie Admin", jPanel8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public boolean clientSideValidation(JFrame frame, String cityId, String cityName)
    {
        if(Pattern.compile("^[1-9]\\d*$").matcher(cityId).matches() && !cityId.equals(""))
        {
            if(Pattern.compile("^[a-zA-Z\\s]*$").matcher(cityName).matches() && !cityName.equals(""))
            {
              return true;
            }
            else
              JOptionPane.showMessageDialog(frame, "City Name is not valid.\nOnly characters and spaces are allowed.", "Alert", JOptionPane.WARNING_MESSAGE); 
        }     
        else
            JOptionPane.showMessageDialog(frame, "City Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);  
      return false;
    }
    private void createCityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCityButtonActionPerformed
        // TODO add your handling code here:
        String cityId = createCityIdField.getText().trim();
        String cityName = createCityNameField.getText().trim();
        boolean passed = clientSideValidation(this, cityId, cityName);
        boolean exists = false;
        if(passed)
        {
            CityDirectory cd = new CityDirectory();
            for(City c: cd.getCityList())
            {
              if(Integer.parseInt(cityId) == c.getCityId())
              {
                JOptionPane.showMessageDialog(this, "City with the given Id already exists\nPlease give another Id to the City..", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;              
              }
              else if(cityName.equals(c.getCityName()))
              {
                JOptionPane.showMessageDialog(this, "City with the given name already exists\nPlease give another name to the City..", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;
              }
            }
            if(!exists)
            {
              int id = Integer.parseInt(cityId);
              String name = cityName;
              City c = new City(id, name);
              int res = CityDirectory.addCity(c);
              if(res > 0)
              {
                JOptionPane.showMessageDialog(this, "Created a new city successfully..", null, JOptionPane.OK_OPTION); 
              }
            }
        }
    }//GEN-LAST:event_createCityButtonActionPerformed
    public void searchData(String type, String searchText)
    {
        int position = -1;
        boolean found = false;
        switch (type) 
        {
            case "cityId":
                cityNameLabel.setVisible(false);
                updateCityNameField.setVisible(false);
                cityUpdateButton.setVisible(false);
                CityDirectory cd = new CityDirectory();
                for(City c: cd.getCityList())
                {
                  if(Integer.parseInt(updateCityIdField.getText()) == c.getCityId())
                  { 
                      found = true;
                      position = c.getCityId();
                      cityNameLabel.setVisible(true);
                      updateCityNameField.setVisible(true);
                      cityUpdateButton.setVisible(true);
                      cityPositionField.setText(Integer.valueOf(position).toString());
                      updateCityNameField.setText(c.getCityName());
                      break;
                  }
                }
                if(!found)
                    JOptionPane.showMessageDialog(this, "City with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
                break;
            case "busId":
                updateBusNameLabel.setVisible(false);
                updateBusFromCityLabel.setVisible(false);
                updateBusToCityLabel.setVisible(false);
                updateBusStartAtLabel.setVisible(false);
                updateBusReachAtLabel.setVisible(false);
                updateBusFareLabel.setVisible(false);
                updateBusTravelDateLabel.setVisible(false);
                
                updateBusNameField.setVisible(false);
                updateBusFromCityCombo.setVisible(false);
                updateBusToCityCombo.setVisible(false);
                updateBusStartAtField.setVisible(false);
                updateBusReachAtField.setVisible(false);
                updateBusFareField.setVisible(false);
                updateBusTravelDateField.setVisible(false);
                
                updateBusButton.setVisible(false);
                
                BusDirectory bd = new BusDirectory();
                for(Bus b : bd.getBusList())
                {
                  if(Integer.parseInt(updateBusIdField.getText()) == b.getId())
                  { 
                        found = true;
                        position = b.getId();
                        updateBusNameLabel.setVisible(true);
                        updateBusFromCityLabel.setVisible(true);
                        updateBusToCityLabel.setVisible(true);
                        updateBusStartAtLabel.setVisible(true);
                        updateBusReachAtLabel.setVisible(true);
                        updateBusFareLabel.setVisible(true);
                        updateBusTravelDateLabel.setVisible(true);

                        updateBusNameField.setVisible(true);
                        updateBusFromCityCombo.setVisible(true);
                        updateBusToCityCombo.setVisible(true);
                        updateBusStartAtField.setVisible(true);
                        updateBusReachAtField.setVisible(true);
                        updateBusFareField.setVisible(true);
                        updateBusTravelDateField.setVisible(true);

                        updateBusButton.setVisible(true);
                        
                        busPositionField.setText(Integer.valueOf(position).toString());
                        updateBusNameField.setText(b.getBusName());
                        CityDirectory cityd = new CityDirectory();
                        updateBusFromCityCombo.removeAllItems();
                        for(City c : cityd.getCityList())
                          updateBusFromCityCombo.addItem(c.getCityName());
                        updateBusFromCityCombo.setSelectedItem(b.getFromCity().getCityName());
                        updateBusToCityCombo.removeAllItems();
                        for(int i = 0; i < updateBusFromCityCombo.getItemCount(); i++)
                        {
                          if(updateBusFromCityCombo.getSelectedItem().toString().equals(updateBusFromCityCombo.getItemAt(i).toString()))
                            continue;           
                          updateBusToCityCombo.addItem(updateBusFromCityCombo.getItemAt(i).toString());
                        }
                        updateBusToCityCombo.setSelectedItem(b.getToCity().getCityName());
                        updateBusStartAtField.setText(b.getDepartureTime());
                        updateBusReachAtField.setText(b.getArrivalTime());
                        updateBusFareField.setText(String.valueOf(b.getFare()));
                        updateBusTravelDateField.setText(b.getTravelDate().toString());
                        break;
                  }
                }
                if(!found)
                    JOptionPane.showMessageDialog(this, "Bus with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
                break;
                
            case "mspId":
                updateMSPNameLabel.setVisible(false);
                updateMSPNameField.setVisible(false);
                updateMSPButton.setVisible(false);
                MobileServiceProviderDirectory mspd = new MobileServiceProviderDirectory();
                for(MobileServiceProvider msp: mspd.getMSPList())
                {
                  if(Integer.parseInt(updateMSPIdField.getText()) == msp.getId())
                  { 
                      found = true;
                      position = msp.getId();
                      updateMSPNameLabel.setVisible(true);
                      updateMSPNameField.setVisible(true);
                      updateMSPButton.setVisible(true);
                      MSPPositionField.setText(Integer.valueOf(position).toString());
                      updateMSPNameField.setText(msp.getProviderName());
                      break;
                  }
                }
                if(!found)
                    JOptionPane.showMessageDialog(this, "Mobile service provider with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
                break;
                
            case "mpId":
                updateMSPNameComboLabel.setVisible(false);
                updateMSPNameCombo.setVisible(false);
                updatePlanNameLabel.setVisible(false);
                updatePlanNameField.setVisible(false);
                updateMPDataLabel.setVisible(false);
                updateMPDataField.setVisible(false);
                updateMPCallsLabel.setVisible(false);
                updateMPCallsField.setVisible(false);
                updateMPValidityLabel.setVisible(false);
                updateMPValidityField.setVisible(false);
                updateMPPriceLabel.setVisible(false);
                updateMPPriceField.setVisible(false);
                updateMPButton.setVisible(false);
                
                MobilePlanDirectory mpd = new MobilePlanDirectory();
                for(MobilePlan mp : mpd.getMPList())
                {
                  if(Integer.parseInt(updateMPIdField.getText()) == mp.getId())
                  {
                    found = true;
                    position = mp.getId();
                    updateMSPNameComboLabel.setVisible(true);
                    updateMSPNameCombo.setVisible(true);
                    updatePlanNameLabel.setVisible(true);
                    updatePlanNameField.setVisible(true);
                    updateMPDataLabel.setVisible(true);
                    updateMPDataField.setVisible(true);
                    updateMPCallsLabel.setVisible(true);
                    updateMPCallsField.setVisible(true);
                    updateMPValidityLabel.setVisible(true);
                    updateMPValidityField.setVisible(true);
                    updateMPPriceLabel.setVisible(true);
                    updateMPPriceField.setVisible(true);
                    updateMPButton.setVisible(true);
                    
                    MPPositionField.setText(Integer.valueOf(position).toString());
                    MobileServiceProviderDirectory mspdd = new MobileServiceProviderDirectory();
                    updateMSPNameCombo.removeAllItems();
                    for(MobileServiceProvider msp : mspdd.getMSPList())
                        updateMSPNameCombo.addItem(msp.getProviderName());
                    updateMSPNameCombo.setSelectedItem(mp.getMobileServiceProvider().getProviderName());
                    updatePlanNameField.setText(mp.getPlanName());
                    updateMPDataField.setText(mp.getData());
                    updateMPCallsField.setText(mp.getCalls());
                    updateMPValidityField.setText(String.valueOf(mp.getValidity()));
                    updateMPPriceField.setText(String.valueOf(mp.getPrice()));
                    break;
                  } 
                }
                if(!found)
                    JOptionPane.showMessageDialog(this, "Mobile plan with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
                break;
        }
    }
    private void citySearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citySearchButtonActionPerformed
        // TODO add your handling code here:
        String searchText = updateCityIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(searchText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "City Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);        
        if(flag)
            searchData("cityId", searchText.trim());
    }//GEN-LAST:event_citySearchButtonActionPerformed

    private void cityUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityUpdateButtonActionPerformed
        // TODO add your handling code here:
        String cityId = updateCityIdField.getText().trim();
        String cityName = updateCityNameField.getText().trim();
        int position = Integer.valueOf(cityPositionField.getText());
        boolean passed = clientSideValidation(this, cityId, cityName);
        boolean exists = false;
        if(passed)
        {
          CityDirectory cd = new CityDirectory();
          for(City c: cd.getCityList())
            {
              if(Integer.parseInt(cityId) == c.getCityId() && c.getCityId() != position)
              {
                JOptionPane.showMessageDialog(this, "City with the given Id already exists\nPlease give another Id to the City..", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;              
              }
              else if(cityName.equals(c.getCityName()) && c.getCityId() != position)
              {
                JOptionPane.showMessageDialog(this, "City with the given name already exists\nPlease give another name to the City..", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;
              }
            }
            if(!exists)
            {
              int id = Integer.parseInt(cityId);
              String name = cityName;
              City c = new City(id, name);
              int res = CityDirectory.updateCity(c, position);
              if(res > 0)
              {
                JOptionPane.showMessageDialog(this, "Updated the city successfully.", null, JOptionPane.OK_OPTION);
                cityPositionField.setText(cityId);
              }
              else
                JOptionPane.showMessageDialog(this, "City does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);  
            }
        }
    }//GEN-LAST:event_cityUpdateButtonActionPerformed

    private void deleteCityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCityButtonActionPerformed
        // TODO add your handling code here:
        String deleteText = deleteCityIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(deleteText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "City Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);       
        if(flag)
        {
          int res = CityDirectory.deleteCity(Integer.parseInt(deleteText));
          if(res > 0)
          {
            JOptionPane.showMessageDialog(this, "Deleted the city successfully..", null, JOptionPane.OK_OPTION);
          }
          else
            JOptionPane.showMessageDialog(this, "City with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteCityButtonActionPerformed

    private void createBusFromCityComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_createBusFromCityComboItemStateChanged
        // TODO add your handling code here:
      if(evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
      {
        createBusToCityCombo.removeAllItems();
        for(int i = 0; i < createBusFromCityCombo.getItemCount(); i++)
        {
          if(createBusFromCityCombo.getSelectedItem().toString().equals(createBusFromCityCombo.getItemAt(i).toString()))
            continue;           
          createBusToCityCombo.addItem(createBusFromCityCombo.getItemAt(i).toString());
        }
      }
    }//GEN-LAST:event_createBusFromCityComboItemStateChanged
    public boolean clientSidevalidation(JFrame frame, String busId, String busName, String startAt, String endAt, String farePrice, String travelDate)
    {
      if(Pattern.compile("^[1-9]\\d*$").matcher(busId).matches())
      {
        if(Pattern.compile("^[a-zA-Z\\s0-9]*$").matcher(busName).matches() && !busName.equals(""))
        {
          if(Pattern.compile("(\\d{2}):(\\d{2}):(\\d{2})").matcher(startAt).matches())
          {
            System.out.println("StartAt is valid.");
            if(Pattern.compile("(\\d{2}):(\\d{2}):(\\d{2})").matcher(endAt).matches())
            {
              System.out.println("Reach At is valid.");
              if(Pattern.compile("^[0-9.]+$").matcher(farePrice).matches() && !farePrice.equals(""))
              {
                System.out.println("Fare is valid.");
                if(Pattern.compile("(\\d{4})-(\\d{2})-(\\d{2})").matcher(travelDate).matches())
                {
                    System.out.println("Travel date is valid.");
                    return true;
                }
                else
                {
                     JOptionPane.showMessageDialog(frame, "Travel date is not valid.\nShould be in the format YYYY-MM-DD.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
              }
              else
                JOptionPane.showMessageDialog(this, "Please enter the fare in positive numbers.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
               JOptionPane.showMessageDialog(frame, "Reach At is not valid.\nShould be in the format HH:MM:SS.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
          }
          else
          {
             JOptionPane.showMessageDialog(frame, "Start At is not valid.\nShould be in the format HH:MM:SS.", "Alert", JOptionPane.WARNING_MESSAGE);
          }
        }
        else
          JOptionPane.showMessageDialog(frame, "Bus Name is not valid.\nOnly Characters, numbers and spaces are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
      }
      else
      {
        JOptionPane.showMessageDialog(frame, "Bus Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
      }
      return false;
    }
    private void createBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBusButtonActionPerformed
        // TODO add your handling code here:
        try
        {
          String busId = createBusIdField.getText().trim();
            String busName = createBusNameField.getText().trim();
            String fromCity = createBusFromCityCombo.getSelectedItem().toString();
            String toCity = createBusToCityCombo.getSelectedItem().toString();
            String startAt = createBusStartAtField.getText().trim();
            String endAt = createBusReachAtField.getText().trim();
            String farePrice = createBusFareField.getText().trim();
            String date = createBusTravelDateField.getText().trim();        
            boolean passed = clientSidevalidation(this, busId, busName, startAt, endAt, farePrice, date);
            boolean exists = false;
            if(passed)
            {
                BusDirectory bd = new BusDirectory();
                for(Bus b: bd.getBusList())
                {
                  if(Integer.parseInt(busId) == b.getId())
                  {
                    JOptionPane.showMessageDialog(this, "Bus with the given Id already exists\nPlease give another Id to the Bus.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;              
                  }
                  else if(busName.equals(b.getBusName()))
                  {
                    JOptionPane.showMessageDialog(this, "Bus with the given name already exists\nPlease give another name to the Bus.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;
                  }
                }
                if(!exists)
                {
                  int id = Integer.parseInt(busId);
                  int fromCityId = CityDirectory.getCityId(fromCity);
                  int toCityId = CityDirectory.getCityId(toCity);             
                  City from = new City(fromCityId, fromCity);
                  City to = new City(toCityId, toCity);
                  double fare = Double.parseDouble(farePrice);
                  LocalDate travelDate = LocalDate.parse(date);
                  Bus bus = new Bus(id, busName, from, to, startAt, endAt, fare, travelDate);
                  int res = BusDirectory.addBus(bus);
                  if(res > 0)
                  {
                    JOptionPane.showMessageDialog(this, "Created a new Bus successfully..", null, JOptionPane.OK_OPTION); 
                  }
                }
            }
        }
        catch(NullPointerException ex)
        {
          JOptionPane.showMessageDialog(this, "Please select the from and to locations.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_createBusButtonActionPerformed

    private void updateBusSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBusSearchButtonActionPerformed
        // TODO add your handling code here:
        String searchText = updateBusIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(searchText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "Bus Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);        
        if(flag)
            searchData("busId", searchText.trim());
    }//GEN-LAST:event_updateBusSearchButtonActionPerformed

    private void updateBusFromCityComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_updateBusFromCityComboItemStateChanged
        // TODO add your handling code here:
        if(evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
        {
            updateBusToCityCombo.removeAllItems();
            for(int i = 0; i < updateBusFromCityCombo.getItemCount(); i++)
            {
              if(updateBusFromCityCombo.getSelectedItem().toString().equals(updateBusFromCityCombo.getItemAt(i).toString()))
                continue;           
              updateBusToCityCombo.addItem(updateBusFromCityCombo.getItemAt(i).toString());
            }
        }
    }//GEN-LAST:event_updateBusFromCityComboItemStateChanged

    private void updateBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBusButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            String busId = updateBusIdField.getText().trim();
            String busName = updateBusNameField.getText().trim();
            String fromCity = updateBusFromCityCombo.getSelectedItem().toString();
            String toCity = updateBusToCityCombo.getSelectedItem().toString();
            String startAt = updateBusStartAtField.getText().trim();
            String endAt = updateBusReachAtField.getText().trim();
            String farePrice = updateBusFareField.getText().trim();
            String date = updateBusTravelDateField.getText().trim(); 
            int position = Integer.valueOf(busPositionField.getText());
            boolean passed = clientSidevalidation(this, busId, busName, startAt, endAt, farePrice, date);
            boolean exists = false;
            if(passed)
            {
                BusDirectory bd = new BusDirectory();
                for(Bus b: bd.getBusList())
                {
                  if(Integer.parseInt(busId) == b.getId() && b.getId() != position)
                  {
                    JOptionPane.showMessageDialog(this, "Bus with the given Id already exists\nPlease give another Id to the Bus.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;              
                  }
                  else if(busName.equals(b.getBusName()) && b.getId() != position)
                  {
                    JOptionPane.showMessageDialog(this, "Bus with the given name already exists\nPlease give another name to the Bus.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;
                  }
                }
                if(!exists)
                {
                  int id = Integer.parseInt(busId);
                  int fromCityId = CityDirectory.getCityId(fromCity);
                  int toCityId = CityDirectory.getCityId(toCity);             
                  City from = new City(fromCityId, fromCity);
                  City to = new City(toCityId, toCity);
                  double fare = Double.parseDouble(farePrice);
                  LocalDate travelDate = LocalDate.parse(date);
                  Bus bus = new Bus(id, busName, from, to, startAt, endAt, fare, travelDate);
                  int res = BusDirectory.updateBus(bus, position);
                  if(res > 0)
                  {
                    JOptionPane.showMessageDialog(this, "Updated the Bus successfully..", null, JOptionPane.OK_OPTION); 
                    busPositionField.setText(busId);
                  }
                  else
                    JOptionPane.showMessageDialog(this, "Bus does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        catch(NullPointerException ex)
        {
          JOptionPane.showMessageDialog(this, "Please select the from and to locations.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateBusButtonActionPerformed

    private void deleteBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBusButtonActionPerformed
        // TODO add your handling code here:
        String deleteText = deleteBusIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(deleteText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "Bus Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);       
        if(flag)
        {
          int res = BusDirectory.deleteBus(Integer.parseInt(deleteText));
          if(res > 0)
          {
            JOptionPane.showMessageDialog(this, "Deleted the Bus successfully..", null, JOptionPane.OK_OPTION);
          }
          else
            JOptionPane.showMessageDialog(this, "Bus with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteBusButtonActionPerformed
    public boolean mspClientSideValidation(JFrame frame, String cityId, String cityName)
    {
        if(Pattern.compile("^[1-9]\\d*$").matcher(cityId).matches() && !cityId.equals(""))
        {
            if(Pattern.compile("^[a-zA-Z\\s]*$").matcher(cityName).matches() && !cityName.equals(""))
            {
              return true;
            }
            else
              JOptionPane.showMessageDialog(frame, "MSP Name is not valid.\nOnly characters and spaces are allowed.", "Alert", JOptionPane.WARNING_MESSAGE); 
        }     
        else
            JOptionPane.showMessageDialog(frame, "MSP Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);  
      return false;
    }
    private void createMSPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMSPButtonActionPerformed
        // TODO add your handling code here:
        String MSPId = createMSPIdField.getText().trim();
        String MSPName = createMSPNameField.getText().trim().toUpperCase();
        boolean passed = mspClientSideValidation(this, MSPId, MSPName);
        boolean exists = false;
        if(passed)
        {
            MobileServiceProviderDirectory mspd = new MobileServiceProviderDirectory();
            for(MobileServiceProvider msp: mspd.getMSPList())
            {
              if(Integer.parseInt(MSPId) == msp.getId())
              {
                JOptionPane.showMessageDialog(this, "MSP with the given Id already exists\nPlease give another Id to the MSP.", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;              
              }
              else if(MSPName.equals(msp.getProviderName()))
              {
                JOptionPane.showMessageDialog(this, "MSP with the given name already exists\nPlease give another name to the MSP.", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;
              }
            }
            if(!exists)
            {
              int id = Integer.parseInt(MSPId);
              String name = MSPName;
              MobileServiceProvider msp = new MobileServiceProvider(id, name);
              int res = MobileServiceProviderDirectory.addMSP(msp);
              if(res > 0)
              {
                JOptionPane.showMessageDialog(this, "Created a new MSP successfully.", null, JOptionPane.OK_OPTION);
                createMSPNameCombo.addItem(name);
              }
            }
        }
    }//GEN-LAST:event_createMSPButtonActionPerformed
    public boolean mpClientSideValidation(JFrame frame, String mpId, String planName, String data, String calls, String validity, String price)
    {
      if(Pattern.compile("^[1-9]\\d*$").matcher(mpId).matches())
      {
        if(Pattern.compile("^[a-zA-Z\\s]*$").matcher(planName).matches() && !planName.equals(""))
        {
          if(Pattern.compile("^[a-zA-Z\\s0-9\\/]*$").matcher(data).matches() && !data.equals(""))
          {
            if(Pattern.compile("^[a-zA-Z\\s0-9\\/]*$").matcher(calls).matches() && !calls.equals(""))
            {
              if(Pattern.compile("^[1-9]\\d*$").matcher(validity).matches())
              {
                if(Pattern.compile("^[0-9.]+$").matcher(price).matches())
                {
                    return true;
                }
                else
                {
                     JOptionPane.showMessageDialog(frame, "Price is not valid.\nOnly positive numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
              }
              else
                JOptionPane.showMessageDialog(this, "Validity is not valid.\nOnly numbers are allowed", "Alert", JOptionPane.WARNING_MESSAGE);
            }
            else
            {
               JOptionPane.showMessageDialog(frame, "Calls is not valid.\nOnly characters, spaces, slashes and numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
            }
          }
          else
          {
             JOptionPane.showMessageDialog(frame, "Data is not valid.\nOnly characters, spaces, slashes and numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
          }
        }
        else
          JOptionPane.showMessageDialog(frame, "Plan name is not valid.\nOnly Characters and spaces are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
      }
      else
      {
        JOptionPane.showMessageDialog(frame, "MP Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
      }
      return false;
    }
    private void createMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMPButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            String mpId = createMPIdField.getText().trim();
            String mSPName = createMSPNameCombo.getSelectedItem().toString();
            String planName = createPlanNameField.getText().trim().toUpperCase();
            String data = createMPDataField.getText().trim().toUpperCase();
            String calls = createMPCallsField.getText().trim().toUpperCase();
            String validity = createMPValidityField.getText().trim(); 
            String price = createMPPriceField.getText().trim();
            boolean passed = mpClientSideValidation(this, mpId, planName, data, calls, validity, price);
            boolean exists = false;
            if(passed)
            {
                MobilePlanDirectory mpd = new MobilePlanDirectory();
                for(MobilePlan mp: mpd.getMPList())
                {
                  if(Integer.parseInt(mpId) == mp.getId())
                  {
                    JOptionPane.showMessageDialog(this, "Mobile Plan with the given Id already exists\nPlease give another Id to the Mobile Plan.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;              
                  }
                  else if(planName.equals(mp.getPlanName()))
                  {
                    JOptionPane.showMessageDialog(this, "Mobile Plan with the given name already exists\nPlease give another name to the Mobile Plan.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;
                  }
                }
                if(!exists)
                {
                  int id = Integer.parseInt(mpId);
                  int mspId = MobileServiceProviderDirectory.getMSPId(mSPName);
                  MobileServiceProvider msp = new MobileServiceProvider(mspId, mSPName);
                  int valid = Integer.parseInt(validity);
                  double amount = Double.parseDouble(price);
                  MobilePlan mp = new MobilePlan(id, msp, planName, data, calls, valid, amount);
                  int res = MobilePlanDirectory.addMP(mp);
                  if(res > 0)
                  {
                    JOptionPane.showMessageDialog(this, "Created a new mobile plan successfully..", null, JOptionPane.OK_OPTION); 
                  }
                }
            }
        }
        catch(NullPointerException ex)
        {
          JOptionPane.showMessageDialog(this, "Please select a mobile service provider.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_createMPButtonActionPerformed

    private void updateMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMPButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            String mpId = updateMPIdField.getText().trim();
            String mSPName = updateMSPNameCombo.getSelectedItem().toString();
            String planName = updatePlanNameField.getText().trim().toUpperCase();
            String data = updateMPDataField.getText().trim().toUpperCase();
            String calls = updateMPCallsField.getText().trim().toUpperCase();
            String validity = updateMPValidityField.getText().trim(); 
            String price = updateMPPriceField.getText().trim();
            int position = Integer.valueOf(MPPositionField.getText());
            boolean passed = mpClientSideValidation(this, mpId, planName, data, calls, validity, price);
            boolean exists = false;
            if(passed)
            {
                MobilePlanDirectory mpd = new MobilePlanDirectory();
                for(MobilePlan mp: mpd.getMPList())
                {
                  if(Integer.parseInt(mpId) == mp.getId() && mp.getId() != position)
                  {
                    JOptionPane.showMessageDialog(this, "Mobile Plan with the given Id already exists\nPlease give another Id to the Mobile Plan.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;              
                  }
                  else if(planName.equals(mp.getPlanName()) && mp.getId() != position)
                  {
                    JOptionPane.showMessageDialog(this, "Mobile Plan with the given name already exists\nPlease give another name to the Mobile Plan.", "Alert", JOptionPane.WARNING_MESSAGE);
                    exists = true;
                    break;
                  }
                }
                if(!exists)
                {
                  int id = Integer.parseInt(mpId);
                  int mspId = MobileServiceProviderDirectory.getMSPId(mSPName);
                  MobileServiceProvider msp = new MobileServiceProvider(mspId, mSPName);
                  int valid = Integer.parseInt(validity);
                  double amount = Double.parseDouble(price);
                  MobilePlan mp = new MobilePlan(id, msp, planName, data, calls, valid, amount);
                  int res = MobilePlanDirectory.updateMP(mp, position);
                  if(res > 0)
                  {
                    JOptionPane.showMessageDialog(this, "Updated the mobile plan successfully..", null, JOptionPane.OK_OPTION);
                    MPPositionField.setText(mpId);             
                  }
                  else
                    JOptionPane.showMessageDialog(this, "Mobile Plan does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        catch(NullPointerException ex)
        {
          JOptionPane.showMessageDialog(this, "Please select a mobile service provider.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_updateMPButtonActionPerformed

    private void updateMSPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMSPButtonActionPerformed
        // TODO add your handling code here:
        String MSPId = updateMSPIdField.getText().trim();
        String MSPName = updateMSPNameField.getText().trim().toUpperCase();
        int position = Integer.valueOf(MSPPositionField.getText());
        boolean passed = mspClientSideValidation(this, MSPId, MSPName);
        boolean exists = false;
        if(passed)
        {
            MobileServiceProviderDirectory mspd = new MobileServiceProviderDirectory();
            for(MobileServiceProvider msp: mspd.getMSPList())
            {
              if(Integer.parseInt(MSPId) == msp.getId() && msp.getId() != position)
              {
                JOptionPane.showMessageDialog(this, "MSP with the given Id already exists\nPlease give another Id to the MSP.", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;              
              }
              else if(MSPName.equals(msp.getProviderName()) && msp.getId() != position)
              {
                JOptionPane.showMessageDialog(this, "MSP with the given name already exists\nPlease give another name to the MSP.", "Alert", JOptionPane.WARNING_MESSAGE);
                exists = true;
                break;
              }
            }
            if(!exists)
            {
              int id = Integer.parseInt(MSPId);
              String name = MSPName;
              MobileServiceProvider msp = new MobileServiceProvider(id, name);
              int res = MobileServiceProviderDirectory.updateMSP(msp, position);
              if(res > 0)
              {
                JOptionPane.showMessageDialog(this, "Updated the MSP successfully.", null, JOptionPane.OK_OPTION);                
                MSPPositionField.setText(MSPId);
                createMSPNameCombo.removeAllItems();
                MobileServiceProviderDirectory mspdd = new MobileServiceProviderDirectory();
                for(MobileServiceProvider ms : mspdd.getMSPList())
                {
                  createMSPNameCombo.addItem(ms.getProviderName());
                }
              }
              else
                JOptionPane.showMessageDialog(this, "MSP does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);  
            }
        }
    }//GEN-LAST:event_updateMSPButtonActionPerformed

    private void updateMSPIdSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMSPIdSearchButtonActionPerformed
        // TODO add your handling code here:
        String searchText = updateMSPIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(searchText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "Mobile service provider Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);        
        if(flag)
            searchData("mspId", searchText.trim());
    }//GEN-LAST:event_updateMSPIdSearchButtonActionPerformed

    private void updateMPIdSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMPIdSearchButtonActionPerformed
        // TODO add your handling code here:
        String searchText = updateMPIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(searchText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "Mobile Plan Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);        
        if(flag)
            searchData("mpId", searchText.trim());
    }//GEN-LAST:event_updateMPIdSearchButtonActionPerformed

    private void deleteMSPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMSPButtonActionPerformed
        // TODO add your handling code here:
        String deleteText = deleteMSPIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(deleteText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "MSP Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);       
        if(flag)
        {
          int res = MobileServiceProviderDirectory.deleteMSP(Integer.parseInt(deleteText));
          if(res > 0)
          {
            JOptionPane.showMessageDialog(this, "Deleted the MSP successfully..", null, JOptionPane.OK_OPTION);
            createMSPNameCombo.removeAllItems();
            MobileServiceProviderDirectory mp = new MobileServiceProviderDirectory();
            for(MobileServiceProvider msp : mp.getMSPList())
            {
              createMSPNameCombo.addItem(msp.getProviderName());
            }
            createMSPNameCombo.setSelectedItem(null);
          }
          else
            JOptionPane.showMessageDialog(this, "MSP with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteMSPButtonActionPerformed

    private void deleteMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMPButtonActionPerformed
        // TODO add your handling code here:
        String deleteText = deleteMPIdField.getText().trim();
        boolean flag = false;
        if(Pattern.compile("^[1-9]\\d*$").matcher(deleteText).matches())
            flag = true;
        else
            JOptionPane.showMessageDialog(this, "Mobile Plan Id is not valid.\nOnly Numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);       
        if(flag)
        {
          int res = MobilePlanDirectory.deleteMP(Integer.parseInt(deleteText));
          if(res > 0)
          {
            JOptionPane.showMessageDialog(this, "Deleted the Mobile Plan successfully..", null, JOptionPane.OK_OPTION);
          }
          else
            JOptionPane.showMessageDialog(this, "Mobile Plan with the given Id does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteMPButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MPPositionField;
    private javax.swing.JTextField MSPPositionField;
    private javax.swing.JTextField busPositionField;
    private javax.swing.JLabel cityNameLabel;
    private javax.swing.JTextField cityPositionField;
    private javax.swing.JButton citySearchButton;
    private javax.swing.JButton cityUpdateButton;
    private javax.swing.JButton createBusButton;
    private javax.swing.JTextField createBusFareField;
    private javax.swing.JComboBox<String> createBusFromCityCombo;
    private javax.swing.JTextField createBusIdField;
    private javax.swing.JTextField createBusNameField;
    private javax.swing.JTextField createBusReachAtField;
    private javax.swing.JTextField createBusStartAtField;
    private javax.swing.JComboBox<String> createBusToCityCombo;
    private javax.swing.JTextField createBusTravelDateField;
    private javax.swing.JButton createCityButton;
    private javax.swing.JTextField createCityIdField;
    private javax.swing.JTextField createCityNameField;
    private javax.swing.JButton createMPButton;
    private javax.swing.JTextField createMPCallsField;
    private javax.swing.JTextField createMPDataField;
    private javax.swing.JTextField createMPIdField;
    private javax.swing.JTextField createMPPriceField;
    private javax.swing.JTextField createMPValidityField;
    private javax.swing.JButton createMSPButton;
    private javax.swing.JTextField createMSPIdField;
    private javax.swing.JComboBox<String> createMSPNameCombo;
    private javax.swing.JTextField createMSPNameField;
    private javax.swing.JTextField createPlanNameField;
    private javax.swing.JButton deleteBusButton;
    private javax.swing.JTextField deleteBusIdField;
    private javax.swing.JButton deleteCityButton;
    private javax.swing.JTextField deleteCityIdField;
    private javax.swing.JButton deleteMPButton;
    private javax.swing.JTextField deleteMPIdField;
    private javax.swing.JButton deleteMSPButton;
    private javax.swing.JTextField deleteMSPIdField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton updateBusButton;
    private javax.swing.JTextField updateBusFareField;
    private javax.swing.JLabel updateBusFareLabel;
    private javax.swing.JComboBox<String> updateBusFromCityCombo;
    private javax.swing.JLabel updateBusFromCityLabel;
    private javax.swing.JTextField updateBusIdField;
    private javax.swing.JTextField updateBusNameField;
    private javax.swing.JLabel updateBusNameLabel;
    private javax.swing.JTextField updateBusReachAtField;
    private javax.swing.JLabel updateBusReachAtLabel;
    private javax.swing.JButton updateBusSearchButton;
    private javax.swing.JTextField updateBusStartAtField;
    private javax.swing.JLabel updateBusStartAtLabel;
    private javax.swing.JComboBox<String> updateBusToCityCombo;
    private javax.swing.JLabel updateBusToCityLabel;
    private javax.swing.JTextField updateBusTravelDateField;
    private javax.swing.JLabel updateBusTravelDateLabel;
    private javax.swing.JTextField updateCityIdField;
    private javax.swing.JTextField updateCityNameField;
    private javax.swing.JButton updateMPButton;
    private javax.swing.JTextField updateMPCallsField;
    private javax.swing.JLabel updateMPCallsLabel;
    private javax.swing.JTextField updateMPDataField;
    private javax.swing.JLabel updateMPDataLabel;
    private javax.swing.JTextField updateMPIdField;
    private javax.swing.JButton updateMPIdSearchButton;
    private javax.swing.JTextField updateMPPriceField;
    private javax.swing.JLabel updateMPPriceLabel;
    private javax.swing.JTextField updateMPValidityField;
    private javax.swing.JLabel updateMPValidityLabel;
    private javax.swing.JButton updateMSPButton;
    private javax.swing.JTextField updateMSPIdField;
    private javax.swing.JButton updateMSPIdSearchButton;
    private javax.swing.JComboBox<String> updateMSPNameCombo;
    private javax.swing.JLabel updateMSPNameComboLabel;
    private javax.swing.JTextField updateMSPNameField;
    private javax.swing.JLabel updateMSPNameLabel;
    private javax.swing.JTextField updatePlanNameField;
    private javax.swing.JLabel updatePlanNameLabel;
    // End of variables declaration//GEN-END:variables
}
