/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.SimpleDateFormat;
import business.mysql.MySql;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.text.ParseException;
import java.time.DayOfWeek;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nbabu
 */
public class BookBusTickets extends javax.swing.JFrame{

    /**
     * Creates new form BookBusTickets
     */
    public BookBusTickets() {
        initComponents();
       try{
    MySql.createConn();
    ResultSet rs = MySql.selectQuery("select * from cities;");
    while(rs.next()){
        fromComboBox.addItem(rs.getString(2));
    }
    
}
 catch(SQLException ex)
          {
            System.out.println(ex);
          }
      finally
          {
            MySql.shutDownConn();
          }
    }
    
    int seat_number=0;
    
    public void ticket_bill(){
        String customer_name = jTextField1.getText();
        String customer_contact = jTextField2.getText();
        String from = (String)fromComboBox.getSelectedItem();
        String to = (String)toComboBox.getSelectedItem();
        String ticket_price = fare.getText();
        int seat = seat_number;
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String date = date_format.format(calendar.getDate());
        ticket.setText(ticket.getText() + "****************************\n");
        ticket.setText(ticket.getText() + "**********BUS TICKET*********\n");
        ticket.setText(ticket.getText() + "*****************************\n");
        ticket.setText(ticket.getText() + "Customer " + "\t" + customer_name + "\n");
        ticket.setText(ticket.getText() + "Contact Number " + "\t" + customer_contact + "\n");
        ticket.setText(ticket.getText() + "From: " + from + "To: " + to + "\n");
        ticket.setText(ticket.getText() + "SeatNo " + "\t" + seat + "\n");
        ticket.setText(ticket.getText() + "Price " + "\t" + ticket_price + "\n");
        ticket.setText(ticket.getText() + "Date " + "\t" + date + "\n");
        ticket.setText(ticket.getText() + "**********^^^^^^^^^**********\n");
        ticket.setText(ticket.getText() + "******Thank You Come Again!!******\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        busesComboBox = new javax.swing.JComboBox<>();
        fromComboBox = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        toComboBox = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticket = new javax.swing.JTextArea();
        jLabel45 = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        calendar = new com.toedter.calendar.JDateChooser();
        seatComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        busIdField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Book Bus Tickets");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Customer Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 145, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setText("Customer Mobile No");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 145, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/busstop.png"))); // NOI18N
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 140, 130));

        jLabel38.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel38.setText("To");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel39.setText("From");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        busesComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                busesComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(busesComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        fromComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fromComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(fromComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jLabel40.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel40.setText("Buses");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        toComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(toComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel42.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel42.setText("Select seat number");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel43.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel43.setText("Select a date");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel44.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 0, 51));
        jLabel44.setText("A Copy of your ticket");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 255));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 110, 30));

        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Book Ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 110, 30));

        ticket.setColumns(20);
        ticket.setRows(5);
        jScrollPane2.setViewportView(ticket);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 250, 190));

        jLabel45.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel45.setText("Price");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        fare.setEnabled(false);
        jPanel1.add(fare, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 140, -1));

        calendar.setDateFormatString("yyyy-MM-dd");
        calendar.setEnabled(false);
        calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                calendarPropertyChange(evt);
            }
        });
        jPanel1.add(calendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 140, -1));

        jPanel1.add(seatComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 100, -1));

        jTabbedPane1.addTab("Book Tickets", jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText(" Booking History");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jTable1.setBackground(new java.awt.Color(204, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bus ID", "Customer ID", "Seat", "Booking Date", "Travel Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 590, 170));

        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jTabbedPane1.addTab("Show Bookings", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("Delete Bookings");

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Enter the Bus ID");

        busIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busIdFieldActionPerformed(evt);
            }
        });

        jTable2.setBackground(new java.awt.Color(255, 255, 204));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bus ID", "Customer ID", "Seat", "Booking Date", "Travel Date"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(406, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(busIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(busIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Delete Bookings", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public boolean clientSideValidation(JFrame frame, String customer_name, String customer_contact)
    {
      if(Pattern.compile("^[a-zA-Z\\s]*$").matcher(customer_name).matches() && !customer_name.equals(""))
         {
           if(Pattern.compile("^\\d{10}$").matcher(customer_contact).matches())
           {
             return true;
           }
           else
            JOptionPane.showMessageDialog(frame, "Contact number is not valid.\nOnly numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);      
         }
         else
            JOptionPane.showMessageDialog(frame, "Customer name is not valid.\nOnly characters and spaces are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);  
      return false;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String customer_name = jTextField1.getText();
        String customer_contact = jTextField2.getText();
        String from = (String)fromComboBox.getSelectedItem();
        String to = (String)toComboBox.getSelectedItem();
        String ticket_price = fare.getText();
        String seat = (String)seatComboBox.getSelectedItem();
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        String date = date_format.format(calendar.getDate());
       
        
        Boolean passed = clientSideValidation(this,customer_name,customer_contact);
        if(passed){
        ticket.setText(ticket.getText() + "****************************\n");
        ticket.setText(ticket.getText() + "**********BUS TICKET*********\n");
        ticket.setText(ticket.getText() + "*****************************\n");
        ticket.setText(ticket.getText() + "Customer " + "\t" + customer_name + "\n");
        ticket.setText(ticket.getText() + "Contact Number " + "\t" + customer_contact + "\n");
        ticket.setText(ticket.getText() + "From: " + from + "To: " + to + "\n");
        ticket.setText(ticket.getText() + "SeatNo " + "\t" + seat + "\n");
        ticket.setText(ticket.getText() + "Price " + "\t" + ticket_price + "\n");
        ticket.setText(ticket.getText() + "Date " + "\t" + date + "\n");
        ticket.setText(ticket.getText() + "**********^^^^^^^^^**********\n");
        ticket.setText(ticket.getText() + "******Thank You Come Again!!******\n");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void fromComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fromComboBoxItemStateChanged
        // TODO add your handling code here:

if(evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
      {
          toComboBox.removeAllItems();
         for(int i = 0; i < fromComboBox.getItemCount(); i++)
         {
           if(fromComboBox.getSelectedItem().toString().equals(fromComboBox.getItemAt(i).toString()))
               continue;           
           toComboBox.addItem(fromComboBox.getItemAt(i).toString());
         }
     }         
    }//GEN-LAST:event_fromComboBoxItemStateChanged

    private void toComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toComboBoxItemStateChanged
        // TODO add your handling code here:
      if(evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED)
      {
        calendar.setEnabled(true);
      }        
    }//GEN-LAST:event_toComboBoxItemStateChanged

    private void calendarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarKeyPressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_calendarKeyPressed

    private void calendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_calendarPropertyChange
        // TODO add your handling code here:
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");        
        if(calendar.getDate() != null)
        {   
            String date = date_format.format(calendar.getDate());
            System.out.println(date);
           
            
            try{
            MySql.createConn(); 
            String from_query = "select id from cities where city_name = " + "\'" + fromComboBox.getSelectedItem().toString() + "\'" + ";";
            ResultSet rs = MySql.selectQuery(from_query);
            
            rs.next();
            int from_id = rs.getInt(1);
            
            String to_query = "select id from cities where city_name = " + "\'" + toComboBox.getSelectedItem().toString() + "\'" + ";";
            rs = MySql.selectQuery(to_query);
            rs.next();
            int to_id = rs.getInt(1);
            String query  = "select CONCAT(bus_name,' ',start_at) from buses where from_city = " + from_id + " and to_city = " + to_id +" and travel_date = " + "\'"+date+ "\'" +";";
            rs = MySql.selectQuery(query);
            
            busesComboBox.removeAllItems();
           
                while(rs.next()){      
            busesComboBox.addItem(rs.getString(1));
            }
            
        
            
        }
        catch(SQLException ex)
                 {
                   System.out.println(ex);
                 }
        finally
              {
                MySql.shutDownConn();
              }                 
        }        
    }//GEN-LAST:event_calendarPropertyChange

    private void busesComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_busesComboBoxItemStateChanged
        // TODO add your handling code here:
              if(evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED){
              

                try{
                    
            String s = (String)busesComboBox.getSelectedItem();
            String first = s.substring(0,s.indexOf(' '));

                 
            MySql.createConn();
            String query = "select fare from buses where bus_name ='"+first+"';";
                System.out.println(query);
            ResultSet rs = MySql.selectQuery(query);
            if(rs.next()){      
                fare.setText(rs.getString(1));
            }
            
            String query1 = "select id from buses where bus_name ='"+first+"'; ";
            rs = MySql.selectQuery(query1);
            rs.next();
            int bus_id = rs.getInt(1);
                    System.out.println(bus_id);
           
           
            String query2  = "select seat_number from bus_bookings where bus_id = " + bus_id +";";
            System.out.println(query2);
            rs = MySql.selectQuery(query2);
            rs.next();
            seatComboBox.removeAllItems();
           int seat_no = rs.getInt(1);
            System.out.println(seat_no);
            
            for(int i = 1; i <31 ; i++)
         {
           if(i==seat_no)
               continue;
           seatComboBox.addItem(String.valueOf(i));
         }
            
            
            
        }
            catch(SQLException ex)
                     {
                       System.out.println(ex);
                     }
            finally
                  {
                    MySql.shutDownConn();
                  }
              }



    }//GEN-LAST:event_busesComboBoxItemStateChanged

    private void busIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busIdFieldActionPerformed

    public void getDataIntoTable(){
         try{
                MySql.createConn();
                String query = "select * from bus_bookings;";
                System.out.println(query);
                ResultSet rs = MySql.selectQuery(query);
                while(rs.next()){  
                    String sr_no = String.valueOf(rs.getInt(1));
                    String user_id = String.valueOf(rs.getInt(2));
                    String bus_id = String.valueOf(rs.getInt(3));
                    String seat_number= String.valueOf(rs.getInt(4));
                    String booking_date = String.valueOf(rs.getDate(5));
                    String travel_date = String.valueOf(rs.getDate(6));
                    
                    String table_data[]={sr_no,user_id,bus_id,seat_number,booking_date,travel_date};
                    DefaultTableModel table_model1 = (DefaultTableModel)jTable1.getModel();
                    DefaultTableModel table_model2 = (DefaultTableModel)jTable2.getModel();

                    table_model1.addRow(table_data);
                    table_model2.addRow(table_data);

                }
            }
        catch(SQLException ex)
                 {
                   System.out.println(ex);
                 }
        finally
              {
                MySql.shutDownConn();
             }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           getDataIntoTable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
                String busID= busIdField.getText();
                MySql.createConn();
                String query=("delete from bus_bookings where bus_id = " + "\'" + busID + "\';");
                int res = MySql.deleteUpdateQuery(query);
                while(true){
                    
                    if(res>0){
                        JOptionPane.showMessageDialog(this, "Deletion successful..", null, JOptionPane.OK_OPTION);
                        
                        getDataIntoTable();
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Deletion not possible..", null, JOptionPane.WARNING_MESSAGE);
                        
                    }
                }
       
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookBusTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookBusTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookBusTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookBusTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookBusTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busIdField;
    private javax.swing.JComboBox<String> busesComboBox;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField fare;
    private javax.swing.JComboBox<String> fromComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> seatComboBox;
    private javax.swing.JTextArea ticket;
    private javax.swing.JComboBox<String> toComboBox;
    // End of variables declaration//GEN-END:variables

   
}
