/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import business.City;
import business.CityDirectory;
import business.Mail;
import business.MovieBooking;
import business.MovieBookingDirectory;
import business.Screen;
import business.ScreenDirectory;
import business.Theatre;
import business.TheatreDirectory;
import business.User;
import business.UserDirectory;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import static userinterface.UserHomePage.balanceLabel;
import static userinterface.UserHomePage.userNameLabel;

/**
 *
 * @author nbabu
 */
public class BookMovieTickets extends javax.swing.JFrame {

    /**
     * Creates new form BookEventTickets
     */
    ArrayList<Theatre> theatreDirectory = new ArrayList<>();
    ArrayList<Screen> screenDirectory = new ArrayList<>();
    ArrayList<MovieBooking> movieBookingDirectory = new ArrayList<>();
    public BookMovieTickets() {
        initComponents();
        CityDirectory cd = new CityDirectory();        
        for(City c : cd.getCityList())
        {
          cityComboBox.addItem(c.getCityName());
        }
        cityComboBox.setSelectedItem(null);
        
        TheatreDirectory td = new TheatreDirectory();
        for(Theatre t: td.getTheatreList())
        {
          theatreDirectory.add(t);
        }
        ScreenDirectory sd = new ScreenDirectory();
        for(Screen s: sd.getScreenList())
        {
          screenDirectory.add(s);
        }
        MovieBookingDirectory mbd = new MovieBookingDirectory();
        for(MovieBooking mb: mbd.getMovieBookingList())
        {
          movieBookingDirectory.add(mb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        theatresComboBox = new javax.swing.JComboBox<>();
        cityComboBox = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        bookTicketButton = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        seatComboBox = new javax.swing.JComboBox<>();
        nL = new javax.swing.JLabel();
        mL = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        movieComboBox = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        screensComboBox = new javax.swing.JComboBox<>();
        dateComboBox = new javax.swing.JComboBox<>();
        timeComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingHistoryTable = new javax.swing.JTable();
        showHistoryButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        movieIdField = new javax.swing.JTextField();
        cancelBookingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("Book Movie Tickets");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jLabel39.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel39.setText("City:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        theatresComboBox.setEnabled(false);
        theatresComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                theatresComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(theatresComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 140, -1));

        cityComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cityComboBoxItemStateChanged(evt);
            }
        });
        cityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(cityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 140, -1));

        jLabel40.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel40.setText("Theatres");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel42.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel42.setText("Select seat number");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        jLabel43.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel43.setText("Select a date");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        clearButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        clearButton.setForeground(new java.awt.Color(102, 102, 255));
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 110, 30));

        bookTicketButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        bookTicketButton.setForeground(new java.awt.Color(102, 102, 255));
        bookTicketButton.setText("Book Ticket");
        bookTicketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bookTicketButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 110, 30));

        jLabel45.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel45.setText("Price");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        priceField.setEnabled(false);
        jPanel1.add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 140, -1));

        seatComboBox.setEnabled(false);
        jPanel1.add(seatComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 140, -1));
        jPanel1.add(nL, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 20, 20));
        jPanel1.add(mL, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 20, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/popcorn.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 140, 130));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 130, 130));

        jLabel41.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel41.setText("Movie Name");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        movieComboBox.setEnabled(false);
        movieComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                movieComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(movieComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 140, -1));

        jLabel46.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel46.setText("Screens");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        screensComboBox.setEnabled(false);
        screensComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                screensComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(screensComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 140, -1));

        dateComboBox.setEnabled(false);
        dateComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dateComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(dateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 140, -1));

        timeComboBox.setEnabled(false);
        timeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                timeComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(timeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 140, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setText("Select a time");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 80, -1));

        jTabbedPane1.addTab("Book Movie Tickets", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText(" Booking History");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        bookingHistoryTable.setBackground(new java.awt.Color(255, 255, 204));
        bookingHistoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking ID", "Customer Name", "Mobile", "Movie ID", "Seat No.", "Booking Date", "Movie Date"
            }
        ));
        jScrollPane1.setViewportView(bookingHistoryTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 730, 200));

        showHistoryButton.setText("Show");
        showHistoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showHistoryButtonActionPerformed(evt);
            }
        });
        jPanel2.add(showHistoryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, -1, -1));

        jTabbedPane1.addTab("Show Bookings", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 204));
        jLabel5.setText("CANCEL Bookings");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 14, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setText("Enter the Movie booking ID");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        movieIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieIdFieldActionPerformed(evt);
            }
        });
        jPanel3.add(movieIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 120, -1));

        cancelBookingButton.setText("Cancel");
        cancelBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBookingButtonActionPerformed(evt);
            }
        });
        jPanel3.add(cancelBookingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 70, -1));

        jTabbedPane1.addTab("Delete Bookings", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        cityComboBox.setSelectedItem(null);
        theatresComboBox.removeAllItems();
        theatresComboBox.setEnabled(false);
        screensComboBox.removeAllItems();
        screensComboBox.setEnabled(false);
        movieComboBox.removeAllItems();
        movieComboBox.setEnabled(false);
        dateComboBox.removeAllItems();
        dateComboBox.setEnabled(false);
        timeComboBox.removeAllItems();
        timeComboBox.setEnabled(false);
        priceField.setText("");
        seatComboBox.removeAllItems();
        seatComboBox.setEnabled(false);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void bookTicketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketButtonActionPerformed
        // TODO add your handling code here:
        try
        {         
            String city = cityComboBox.getSelectedItem().toString();
            String theatre = theatresComboBox.getSelectedItem().toString();
            String screenId = screensComboBox.getSelectedItem().toString();
            String movie = movieComboBox.getSelectedItem().toString();
            String date = dateComboBox.getSelectedItem().toString();
            String time = timeComboBox.getSelectedItem().toString();
            int seatNumber = Integer.parseInt(seatComboBox.getSelectedItem().toString());
            double price = Double.parseDouble(priceField.getText());
            UserDirectory ud = new UserDirectory();
            int userId = 0;
            double balance = 0;
            String email = "";
            for(User user : ud.getUserList())
            {
              if(user.getUserName().equals(userNameLabel.getText()))
              {
                userId = user.getId();
                balance = user.getWallet_balance();
                email = user.getEmail();
              }
            }
            double available_balance = balance - price;
            if(available_balance < 0)
            {
              JOptionPane.showMessageDialog(this, "The available wallet balance is less than the amount \nthat you're trying to transfer.", "Alert", JOptionPane.WARNING_MESSAGE);
              return;
            }
            int res = MovieBookingDirectory.seatFilled(Integer.parseInt(screenId), seatNumber);
            if(res > 0)
            {
               JOptionPane.showMessageDialog(this, "Someone had already booked the seat, please book another seat.", "Alert", JOptionPane.WARNING_MESSAGE);
               return;
            }
            User user = new User(userId, "", "", 0, "", balance);           
            Screen screen = new Screen(Integer.parseInt(screenId), null, null, null, null, 0);
            MovieBooking mb = new MovieBooking(0, user, screen, seatNumber, null);
            int res1 = MovieBookingDirectory.addMovieBooking(mb);
            if(res1 > 0)
            {
               JOptionPane.showMessageDialog(this, "Booked the ticket successfully.", null, JOptionPane.OK_OPTION);
               int res2 = UserDirectory.updateBalance(userId, available_balance);
               if(res2 > 0)
               {
                 balanceLabel.setText("$ " + available_balance);
                 String message = "****************************\n";
                 message += "**********Movie TICKET*********\n";
                 message += "*****************************\n";
                 message += "City: " + city + "\n";
                 message += "Theatre: " + theatre + "\n";
                 message += "Screen: " + screenId + "\n";
                 message += "Movie: " + movie + "\n";
                 message += "Date: " + date + "\n";
                 message += "Time: " + time + "\n";
                 message += "Price: " + price + "\n";
                 message += "seat: " + seatNumber + "\n"; 
                 message += "**********^^^^^^^^^**********\n";
                 message += "******Thank You Come Again!!******\n";
                 Mail.sendMail(email, message);
               }
            }
        }
        catch(NullPointerException np)
        {
           JOptionPane.showMessageDialog(this, "Please fill all the necessary fields.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bookTicketButtonActionPerformed

    private void cityComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cityComboBoxItemStateChanged
        // TODO add your handling code here:
        if(evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) 
        {
          theatresComboBox.setEnabled(true);
          String cityName = cityComboBox.getSelectedItem().toString();
          theatresComboBox.removeAllItems();
          for(Theatre t : theatreDirectory)
          {
            if(t.getCity().getCityName().equals(cityName))
            {
              theatresComboBox.addItem(t.getTheatreName());
            }            
          }
        }
    }//GEN-LAST:event_cityComboBoxItemStateChanged

    private void theatresComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_theatresComboBoxItemStateChanged
        // TODO add your handling code here:
        if(evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) 
        {
          screensComboBox.setEnabled(true);
          String theatreName = theatresComboBox.getSelectedItem().toString();
          screensComboBox.removeAllItems();
          for(Screen s : screenDirectory)
          {
            if(s.getTheatre().getTheatreName().equals(theatreName))
            {
              screensComboBox.addItem(String.valueOf(s.getId()));
            }            
          }
        }
    }//GEN-LAST:event_theatresComboBoxItemStateChanged

    private void movieIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieIdFieldActionPerformed

    private void showHistoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHistoryButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showHistoryButtonActionPerformed
    public boolean clientSideValidation(JFrame frame, String bookingId) {
        if (Pattern.compile("^[1-9]\\d*$").matcher(bookingId).matches()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(frame, "Booking Id is not valid.\nOnly numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);
        }
        return false;
    }
    private void cancelBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBookingButtonActionPerformed
        // TODO add your handling code here:
        String movieID = movieIdField.getText().trim();
        boolean passed = clientSideValidation(this, movieID);
        if (passed)
        {
            
        }
    }//GEN-LAST:event_cancelBookingButtonActionPerformed

    private void cityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityComboBoxActionPerformed

    private void movieComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_movieComboBoxItemStateChanged
        if (evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) 
        {
            dateComboBox.setEnabled(true);
            int screenId = Integer.parseInt(screensComboBox.getSelectedItem().toString());
            String movieName = movieComboBox.getSelectedItem().toString();
            dateComboBox.removeAllItems();
            for(Screen s : screenDirectory)
            {
              if(s.getId() == screenId && s.getMovie().getMovieName().equals(movieName))
              {
                dateComboBox.addItem(s.getMovieDate().toString());
              }            
            }
        }
    }//GEN-LAST:event_movieComboBoxItemStateChanged

    private void screensComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_screensComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) 
        {
            movieComboBox.setEnabled(true);
            int screenId = Integer.parseInt(screensComboBox.getSelectedItem().toString());
            movieComboBox.removeAllItems();
            for(Screen s : screenDirectory)
            {
              if(s.getId() == screenId)
              {
                movieComboBox.addItem(s.getMovie().getMovieName());
              }            
            }
        }
    }//GEN-LAST:event_screensComboBoxItemStateChanged

    private void dateComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dateComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) 
        {
            timeComboBox.setEnabled(true);
            int screenId = Integer.parseInt(screensComboBox.getSelectedItem().toString());
            String movieName = movieComboBox.getSelectedItem().toString();
            String movieDate = dateComboBox.getSelectedItem().toString();
            timeComboBox.removeAllItems();
            for(Screen s : screenDirectory)
            {
              if(s.getId() == screenId && s.getMovie().getMovieName().equals(movieName) && s.getMovieDate().toString().equals(movieDate))
              {
                timeComboBox.addItem(s.getMovieTime().toString());
              }            
            }
        }
    }//GEN-LAST:event_dateComboBoxItemStateChanged

    private void timeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_timeComboBoxItemStateChanged
        // TODO add your handling code here:
        if (evt != null && evt.getSource().toString() != null && evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) 
        {
            int screenId = Integer.parseInt(screensComboBox.getSelectedItem().toString());
            String movieName = movieComboBox.getSelectedItem().toString();
            String movieDate = dateComboBox.getSelectedItem().toString();
            String movieTime = timeComboBox.getSelectedItem().toString();
            seatComboBox.setEnabled(true);
            seatComboBox.removeAllItems();
            ScreenDirectory sd = new ScreenDirectory();
            for(Screen s : sd.getScreenList())
            {
              if(s.getId() == screenId && s.getMovie().getMovieName().equals(movieName) && s.getMovieDate().toString().equals(movieDate) && s.getMovieTime().toString().equals(movieTime))
              {
                priceField.setText(String.valueOf(s.getPrice()));
              }           
            }
            ArrayList<Integer> seats = new ArrayList<>();
            for(int i = 1; i < 61 ; i++)
            {                  
              seats.add(i);
            }
            for(MovieBooking mb : movieBookingDirectory)
            {
              if(mb.getScreen().getId() == screenId)
              {
                seats.remove(Integer.valueOf(mb.getSeatNumber()));
              }              
            }
            seatComboBox.removeAllItems();
            for(int i : seats)
            {
              seatComboBox.addItem(String.valueOf(i));
            } 
        }
    }//GEN-LAST:event_timeComboBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookMovieTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookMovieTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookMovieTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookMovieTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookMovieTickets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookTicketButton;
    private javax.swing.JTable bookingHistoryTable;
    private javax.swing.JButton cancelBookingButton;
    private javax.swing.JComboBox<String> cityComboBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> dateComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel mL;
    private javax.swing.JComboBox<String> movieComboBox;
    private javax.swing.JTextField movieIdField;
    private javax.swing.JLabel nL;
    private javax.swing.JTextField priceField;
    private javax.swing.JComboBox<String> screensComboBox;
    private javax.swing.JComboBox<String> seatComboBox;
    private javax.swing.JButton showHistoryButton;
    private javax.swing.JComboBox<String> theatresComboBox;
    private javax.swing.JComboBox<String> timeComboBox;
    // End of variables declaration//GEN-END:variables

}
