/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import business.BankAccountDirectory;
import business.UserDirectory;
import business.mysql.MySql;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static userinterface.UserHomePage.balanceLabel;
import static userinterface.UserHomePage.userNameLabel;

/**
 *
 * @author nbabu
 */
public class MoneyToBank extends javax.swing.JFrame {

    /**
     * Creates new form MoneyToBank
     */
    public MoneyToBank() {
        initComponents();
        try
        {
          MySql.createConn();
          ResultSet rs = UserDirectory.getUserId(userNameLabel.getText());
          rs.next();
          int user_id = rs.getInt(1);
          rs = BankAccountDirectory.getAccountNumbers(user_id);
          while(rs.next()){
            bankAccCombo.addItem(rs.getString(1));
          }
        }
        catch(SQLException ex)
        {
          System.out.println(ex);
        }
        finally
        {
          MySql.shutDownConn();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bankAccCombo = new javax.swing.JComboBox<>();
        amountField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sendToBankButton = new javax.swing.JButton();
        amountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Bank Accounts:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 124, -1, -1));

        bankAccCombo.setBackground(new java.awt.Color(0, 0, 0));
        bankAccCombo.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(bankAccCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 150, -1));

        amountField.setBackground(new java.awt.Color(0, 0, 0));
        amountField.setForeground(new java.awt.Color(204, 204, 204));
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountFieldKeyReleased(evt);
            }
        });
        jPanel1.add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 150, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Amount:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, -1));

        sendToBankButton.setBackground(new java.awt.Color(102, 204, 255));
        sendToBankButton.setForeground(new java.awt.Color(255, 255, 255));
        sendToBankButton.setText("Transfer to bank");
        sendToBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToBankButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sendToBankButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 260, -1));
        jPanel1.add(amountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 20, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Transfer Money to Bank");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void amountFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyReleased
        // TODO add your handling code here:
        String money = amountField.getText().trim();
        if(Pattern.compile("^[0-9.]+$").matcher(money).matches() && !money.equals(""))
        {
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(amountLabel.getWidth(), amountLabel.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          amountLabel.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          amountLabel.setIcon(icon);
        }
    }//GEN-LAST:event_amountFieldKeyReleased
    public boolean clientSideValidation(JFrame frame, String amount)
    {
        if(Pattern.compile("^[0-9.]+$").matcher(amount).matches() && !amount.equals(""))
        {
          return true;
        }
        else
          JOptionPane.showMessageDialog(this, "Please enter the amount in positive numbers.", "Alert", JOptionPane.WARNING_MESSAGE);
      return false;
    }
    private void sendToBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToBankButtonActionPerformed
        // TODO add your handling code here:        
        String amount = amountField.getText().trim();
        boolean passed = clientSideValidation(this, amount);
        if(passed)
        {
          try
          {
            String bankAccount = bankAccCombo.getSelectedItem().toString();
            double money = Double.parseDouble(amount);
            MySql.createConn();
            ResultSet rs = UserDirectory.getBalance(userNameLabel.getText());
            rs.next();
            double balance = rs.getDouble(1);
            double available_balance = balance - money;
            if(available_balance < 0)
            {
              JOptionPane.showMessageDialog(this, "The available wallet balance is less than the amount \nthat you're trying to transfer.", "Alert", JOptionPane.WARNING_MESSAGE);
              return;
            }            
            int res = BankAccountDirectory.addMoneyToBank(money, bankAccount);
            if(res > 0)
            {
              JOptionPane.showMessageDialog(this, "Amount transferred to bank successfully.", null, JOptionPane.OK_OPTION);              
              res = UserDirectory.deductMoney(money, userNameLabel.getText());
              if(res > 0)
              {
                balanceLabel.setText("$ " + available_balance);
              }
            }
            else
              JOptionPane.showMessageDialog(this, "The selected bank account does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
          }
          catch(SQLException ex)
          {
            System.out.println(ex);
          }
          catch(NullPointerException ex)
          {
            JOptionPane.showMessageDialog(this, "The selected bank account does not exist.", "Alert", JOptionPane.WARNING_MESSAGE);
          }
          finally
          {
            MySql.shutDownConn();
          }
        }
        
    }//GEN-LAST:event_sendToBankButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyToBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyToBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyToBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyToBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoneyToBank().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel amountLabel;
    private javax.swing.JComboBox<String> bankAccCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton sendToBankButton;
    // End of variables declaration//GEN-END:variables
}
