/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import business.Mail;
import business.mysql.MySql;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author nbabu
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mobileField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        eV = new javax.swing.JLabel();
        uV = new javax.swing.JLabel();
        mV = new javax.swing.JLabel();
        pV = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 800));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 230, 310, 314));

        jPanel2.setBackground(new java.awt.Color(116, 185, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registration");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 136, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 70, -1));

        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailFieldKeyReleased(evt);
            }
        });
        jPanel2.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 120, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Username:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 70, 20));

        userNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameFieldKeyReleased(evt);
            }
        });
        jPanel2.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Mobile:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 70, -1));

        mobileField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileFieldKeyReleased(evt);
            }
        });
        jPanel2.add(mobileField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Password:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 70, -1));

        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passFieldKeyReleased(evt);
            }
        });
        jPanel2.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 120, -1));

        signUpButton.setText("Signup");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });
        jPanel2.add(signUpButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 230, -1));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 230, -1));

        eV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eV.setPreferredSize(new java.awt.Dimension(7, 17));
        jPanel2.add(eV, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 20, 23));
        jPanel2.add(uV, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 20, 23));
        jPanel2.add(mV, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 20, 23));
        jPanel2.add(pV, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 20, 23));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.show();
        dispose();
    }//GEN-LAST:event_loginButtonActionPerformed
    public static boolean clientSideVlaidation(JFrame frame, String email, String username, String mobile, String password)
    {
         if(Pattern.compile("^[a-zA-Z\\s]*$").matcher(username).matches() && !username.equals(""))
         {
           System.out.println("User Name is valid.");
           if(Pattern.compile("^\\d{10}$").matcher(mobile).matches())
           {
             System.out.println("Mobile number is valid.");
             if(Pattern.compile("^[A-Za-z0-9+_.-]+@(.+)$").matcher(email).matches() && !email.equals(""))
             {
                System.out.println("Email is valid");
                 
                  if(Pattern.compile("^(?=.*\\d).{4,15}$").matcher(password).matches())
                      return true;
                  else
                    JOptionPane.showMessageDialog(frame, "Password is not valid.\nPassword must contain at least 4 characters with at least one digit.", "Alert", JOptionPane.WARNING_MESSAGE);    
             } 
             else
              JOptionPane.showMessageDialog(frame, "Email is not valid.\nPlease enter a valid email.", "Alert", JOptionPane.WARNING_MESSAGE);
           }
           else
            JOptionPane.showMessageDialog(frame, "Mobile number is not valid.\nOnly numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);      
         }
         else
            JOptionPane.showMessageDialog(frame, "Username is not valid.\nOnly characters and numbers are allowed.", "Alert", JOptionPane.WARNING_MESSAGE);  
      return false;     
    }
    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        // TODO add your handling code here:
        String email = emailField.getText();
        String userName = userNameField.getText();
        String mobile = mobileField.getText();
        String password = new String(passField.getPassword());
        boolean passed = clientSideVlaidation(this, email, userName, mobile, password);
        if(passed)
        {
          try
          {
            MySql.createConn();
            boolean exists = false;            
            ResultSet rs = MySql.selectQuery("select * from users;");
            while(rs.next())
            {
              if(userName.equals(rs.getString(2)))
              {
                exists = true;
                JOptionPane.showMessageDialog(this, "User with the given name already exists..", "Alert", JOptionPane.WARNING_MESSAGE);
                break;
              }
              else if(email.equals(rs.getString(3)))
              {
                exists = true;
                JOptionPane.showMessageDialog(this, "User with the given email already exists..", "Alert", JOptionPane.WARNING_MESSAGE);
                break;
              }
              else if(mobile.equals(rs.getString(4)))
              {
                exists = true;
                JOptionPane.showMessageDialog(this, "User with the given mobile already exists..", "Alert", JOptionPane.WARNING_MESSAGE);
                break;
              }
            }
            if(!exists)
            {
              String code = "";
              for(int i = 0; i < 6; i++)
                code += (int)(Math.random() * 6);
//              String query = "insert into registration(username, email, mobile, password, code) values(" + "\'" + userName + "\'" +"," + "\'" + email + "\'" + "," + "\'" + mobile + "\'" + ","  + "\'" + password + "\'" + "," + "\'" + code + "\'" + ");";
//              System.out.println(query);
//              int res = MySql.insertUpdateQuery(query);
                Mail mail = new Mail(email, code);
                mail.sendMail();               
                while(true){
                    String userCode = JOptionPane.showInputDialog(this,"Please enter the code that is sent to your Email Id."); 
                    if(userCode.equals(code))
                    {
                      int res = MySql.insertUpdateQuery("insert into users(username, email, mobile, password) values(" + "\'" + userName + "\'" +"," + "\'" + email + "\'" + "," + "\'" + mobile + "\'" + ","  + "\'" + password + "\'" + ");");
                      if(res > 0)
                      {
                        JOptionPane.showMessageDialog(this, "Registration successful, please login..", null, JOptionPane.OK_OPTION);
                        break;
                      }
                    }
                    else
                    {
                      JOptionPane.showMessageDialog(this, "The code entered is incorrect, please enter the correct code.", "Alert", JOptionPane.WARNING_MESSAGE);
                    }               
              }
            }
          }
          catch(SQLException ex)
          {
            System.out.println(ex);
          }
          finally
          {
            MySql.shutDownConn();
          }
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void emailFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyReleased
        // TODO add your handling code here:
        String email = emailField.getText();
        if(Pattern.compile("^[A-Za-z0-9+_.-]+@(.+)$").matcher(email).matches() && !email.equals(""))
        {
//          File f = new File("target/classes/images/accept.png");
//          System.out.println(f.getAbsolutePath());
//          if(f.exists())
//            System.out.println("Present");
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(eV.getWidth(), eV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          eV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          eV.setIcon(icon);
        }
    }//GEN-LAST:event_emailFieldKeyReleased

    private void userNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyReleased
        // TODO add your handling code here:
        String userName = userNameField.getText();
        if(Pattern.compile("^[a-zA-Z\\s]*$").matcher(userName).matches() && !userName.equals(""))
        {
//          File f = new File("/Users/nbabu/Desktop/AED/Assignments/AED_FINAL_PROJECT/PaymentInterfaceProject/src/main/java/images/accept.png");
//          if(f.exists())
//            System.out.println("Present");
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(uV.getWidth(), uV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          uV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          uV.setIcon(icon);
        }
    }//GEN-LAST:event_userNameFieldKeyReleased

    private void mobileFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileFieldKeyReleased
        // TODO add your handling code here:
        String mobile = mobileField.getText();
        if(Pattern.compile("^\\d{10}$").matcher(mobile).matches() && !mobile.equals(""))
        {
//          File f = new File("/Users/nbabu/Desktop/AED/Assignments/AED_FINAL_PROJECT/PaymentInterfaceProject/src/main/java/images/accept.png");
//          if(f.exists())
//            System.out.println("Present");
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(mV.getWidth(), mV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          mV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          mV.setIcon(icon);
        }
    }//GEN-LAST:event_mobileFieldKeyReleased

    private void passFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyReleased
        // TODO add your handling code here:
        String password = new String(passField.getPassword());
        if(Pattern.compile("^(?=.*\\d).{4,15}$").matcher(password).matches() && !password.equals(""))
        {
//          File f = new File("/Users/nbabu/Desktop/AED/Assignments/AED_FINAL_PROJECT/PaymentInterfaceProject/src/main/java/images/accept.png");
//          if(f.exists())
//            System.out.println("Present");
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(pV.getWidth(), pV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          pV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          pV.setIcon(icon);
        }
    }//GEN-LAST:event_passFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eV;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel mV;
    private javax.swing.JTextField mobileField;
    private javax.swing.JLabel pV;
    private javax.swing.JPasswordField passField;
    private javax.swing.JButton signUpButton;
    private javax.swing.JLabel uV;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
