/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

/**
 *
 * @author nbabu
 */
import business.Mail;
import business.User;
import business.UserDirectory;
import business.mysql.MySql;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static userinterface.Registration.clientSideVlaidation;

public class UserHomePage extends javax.swing.JFrame {

    /**
     * Creates new form userHomePage
     */
    public UserHomePage(String userName) {
        initComponents();
        userNameLabel.setText(userName);
        try
        {
          UserDirectory ud = new UserDirectory();
          for(User user: ud.getUserList())
          {
            if(user.getUserName().equals(userNameLabel.getText()))
            {
                userNameField.setText(user.getUserName());
                emailField.setText(user.getEmail());
                mobileField.setText(String.valueOf(user.getMobile()));
                passField.setText(user.getPassword());
                balanceLabel.setText("$ " + user.getWallet_balance());
                break;
            }
          }        
        }
        catch(Exception ex)
        {
          System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        moneyToWalletLabel = new javax.swing.JLabel();
        moneyToBankLabel = new javax.swing.JLabel();
        moneyToOthersWalletLabel = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        spendAnalyticsLabel = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        bookEventTicketsLabel = new javax.swing.JLabel();
        bookMovieTicketsLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bookBusTicketsLabel = new javax.swing.JLabel();
        bookTrainTicketsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mobileRechargeLabel = new javax.swing.JLabel();
        electricityBillLabel = new javax.swing.JLabel();
        gasBillLabel = new javax.swing.JLabel();
        waterBillLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        mobileField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        passField = new javax.swing.JPasswordField();
        updateButton = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        uV = new javax.swing.JLabel();
        mV = new javax.swing.JLabel();
        eV = new javax.swing.JLabel();
        pV = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));

        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 102));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(userNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 0, 142, 25));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("<html> <p>Add Money from</p> <p>bank to the Wallet</p> </html>");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("<html>\n<p>Transfer Money from</p>\n<p>Wallet to others Wallet</p>\n</html>");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 204));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("<html> <p>Transfer Money from</p> <p>Wallet to the Bank</p> </html>");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, -1, -1));

        moneyToWalletLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyToWalletLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet.png"))); // NOI18N
        moneyToWalletLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyToWalletLabelMouseClicked(evt);
            }
        });
        jPanel1.add(moneyToWalletLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 70, -1));

        moneyToBankLabel.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        moneyToBankLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyToBankLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet 2.png"))); // NOI18N
        moneyToBankLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyToBankLabelMouseClicked(evt);
            }
        });
        jPanel1.add(moneyToBankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 70, 70));

        moneyToOthersWalletLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moneyToOthersWalletLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet 3.png"))); // NOI18N
        moneyToOthersWalletLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moneyToOthersWalletLabelMouseClicked(evt);
            }
        });
        jPanel1.add(moneyToOthersWalletLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 70, 70));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 204));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("<html>\n<p>View Spend</p>\n<p>Analytics</p>\n</html>");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 387, 130, 30));

        spendAnalyticsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        spendAnalyticsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/analytics.png"))); // NOI18N
        spendAnalyticsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spendAnalyticsLabelMouseClicked(evt);
            }
        });
        jPanel1.add(spendAnalyticsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 80, 70));

        jLabel25.setBackground(new java.awt.Color(204, 204, 204));
        jLabel25.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 204));
        jLabel25.setText("Wallet Balance:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 87, -1, 30));

        balanceLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(balanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 160, 30));

        jTabbedPane1.addTab("Payment", jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("Book Event Tickets");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        bookEventTicketsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placard.png"))); // NOI18N
        bookEventTicketsLabel.setText("jLabel1");
        bookEventTicketsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookEventTicketsLabelMouseClicked(evt);
            }
        });
        jPanel2.add(bookEventTicketsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 130, 110));

        bookMovieTicketsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/video-player.png"))); // NOI18N
        bookMovieTicketsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookMovieTicketsLabelMouseClicked(evt);
            }
        });
        jPanel2.add(bookMovieTicketsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 150, 140));

        jLabel16.setForeground(new java.awt.Color(204, 204, 204));
        jLabel16.setText("Book Movie Tickets");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, -1));

        jTabbedPane1.addTab("Entertainment", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookBusTicketsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookBusTicketsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bus.png"))); // NOI18N
        bookBusTicketsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookBusTicketsLabelMouseClicked(evt);
            }
        });
        jPanel3.add(bookBusTicketsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 170, 130));

        bookTrainTicketsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bookTrainTicketsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/train.png"))); // NOI18N
        bookTrainTicketsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookTrainTicketsLabelMouseClicked(evt);
            }
        });
        jPanel3.add(bookTrainTicketsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 127, 140, 70));

        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("Book Bus Tickets");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, -1));

        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("Book Train Tickets");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 120, 20));

        jTabbedPane1.addTab("Travel", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mobile Recharge");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Electricity bill payment");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gas Bill");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Water bill");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 140, -1));

        mobileRechargeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/recharge.png"))); // NOI18N
        mobileRechargeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobileRechargeLabelMouseClicked(evt);
            }
        });
        jPanel4.add(mobileRechargeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 104, -1, 60));

        electricityBillLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/electricity-bill.png"))); // NOI18N
        electricityBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electricityBillLabelMouseClicked(evt);
            }
        });
        jPanel4.add(electricityBillLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        gasBillLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gas.png"))); // NOI18N
        gasBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gasBillLabelMouseClicked(evt);
            }
        });
        jPanel4.add(gasBillLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        waterBillLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/faucet.png"))); // NOI18N
        waterBillLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                waterBillLabelMouseClicked(evt);
            }
        });
        jPanel4.add(waterBillLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        jTabbedPane1.addTab("Recharge and Utilities", jPanel4);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Username:");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        userNameField.setBackground(new java.awt.Color(0, 0, 0));
        userNameField.setForeground(new java.awt.Color(204, 204, 204));
        userNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameFieldKeyReleased(evt);
            }
        });
        jPanel6.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 130, -1));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setForeground(new java.awt.Color(204, 204, 204));
        jLabel21.setText("Mobile:");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        emailField.setBackground(new java.awt.Color(0, 0, 0));
        emailField.setForeground(new java.awt.Color(204, 204, 204));
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailFieldKeyReleased(evt);
            }
        });
        jPanel6.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 130, -1));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setForeground(new java.awt.Color(204, 204, 204));
        jLabel22.setText("Email:");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        mobileField.setBackground(new java.awt.Color(0, 0, 0));
        mobileField.setForeground(new java.awt.Color(204, 204, 204));
        mobileField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileFieldKeyReleased(evt);
            }
        });
        jPanel6.add(mobileField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 130, -1));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setForeground(new java.awt.Color(204, 204, 204));
        jLabel26.setText("Password:");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        passField.setBackground(new java.awt.Color(0, 0, 0));
        passField.setForeground(new java.awt.Color(204, 204, 204));
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passFieldKeyReleased(evt);
            }
        });
        jPanel6.add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 130, -1));

        updateButton.setBackground(new java.awt.Color(102, 204, 255));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel6.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 210, -1));

        jLabel27.setBackground(new java.awt.Color(102, 204, 255));
        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Update Profile");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 230, 30));

        uV.setBackground(new java.awt.Color(0, 0, 0));
        uV.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(uV, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 20, 20));

        mV.setBackground(new java.awt.Color(0, 0, 0));
        mV.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(mV, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 20, 20));

        eV.setBackground(new java.awt.Color(0, 0, 0));
        eV.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(eV, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 20, 20));

        pV.setBackground(new java.awt.Color(0, 0, 0));
        pV.setForeground(new java.awt.Color(204, 204, 204));
        jPanel6.add(pV, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 20, 20));

        logoutButton.setBackground(new java.awt.Color(102, 204, 255));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel6.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 210, -1));

        jTabbedPane1.addTab("Profile", jPanel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookBusTicketsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBusTicketsLabelMouseClicked
        // TODO add your handling code here:
        BookBusTickets bt = new BookBusTickets();
        bt.setVisible(true);
    }//GEN-LAST:event_bookBusTicketsLabelMouseClicked

    private void moneyToWalletLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyToWalletLabelMouseClicked
        // TODO add your handling code here:
        AddMoneyToWallet amw = new AddMoneyToWallet(userNameLabel.getText());
        amw.setVisible(true);
    }//GEN-LAST:event_moneyToWalletLabelMouseClicked

    private void moneyToOthersWalletLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyToOthersWalletLabelMouseClicked
        // TODO add your handling code here:
        MoneyToOthersWallet mtw = new MoneyToOthersWallet();
        mtw.setVisible(true);
    }//GEN-LAST:event_moneyToOthersWalletLabelMouseClicked

    private void moneyToBankLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moneyToBankLabelMouseClicked
        // TODO add your handling code here:
        MoneyToBank mtb = new MoneyToBank();
        mtb.setVisible(true);
    }//GEN-LAST:event_moneyToBankLabelMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String userName = userNameField.getText().trim();
        String email = emailField.getText().trim();        
        String mobile = mobileField.getText().trim();
        String password = new String(passField.getPassword());
        int position = 0;
        boolean passed = clientSideVlaidation(this, email, userName, mobile, password);
        if(passed)
        {
          try
          {
             boolean exists = false;            
             UserDirectory ud = new UserDirectory();
             ArrayList<User> userDirectory = ud.getUserList();
             for(User user: userDirectory)
             {
               if(user.getUserName().equals(userNameLabel.getText()))
               {
                    position = user.getId();
                    userDirectory.remove(user);
                    break;
               }
             }
             for(User user: userDirectory)
             {
                if(user.getUserName().equals(userNameLabel.getText()))
                    position = user.getId();
                if(userName.equals(user.getUserName()))
                {
                  exists = true;                  
                  JOptionPane.showMessageDialog(this, "User with the given name already exists.", "Alert", JOptionPane.WARNING_MESSAGE);
                  break;
                }
                else if(email.equals(user.getEmail()))
                {
                  exists = true;
                  JOptionPane.showMessageDialog(this, "User with the given email already exists.", "Alert", JOptionPane.WARNING_MESSAGE);
                  break;
                }
                else if(Long.parseLong(mobile) == user.getMobile())
                {
                  exists = true;
                  JOptionPane.showMessageDialog(this, "User with the given mobile already exists.", "Alert", JOptionPane.WARNING_MESSAGE);
                  break;
                }
             }
            if(!exists)
            {
              String code = "";
              for(int i = 0; i < 6; i++)
                code += (int)(Math.random() * 6);
              
              Mail mail = new Mail(email, code);
              mail.sendMail();        
              while(true)
              {
                String userCode = JOptionPane.showInputDialog(this,"Please enter the code that is sent to your Email Id."); 
                if(userCode.equals(code))
                {
                    User user = new User(0, userName, email, Long.parseLong(mobile), password, 0);
                    int res = UserDirectory.updateUser(user, position);
                    if(res > 0)
                    {
                        JOptionPane.showMessageDialog(this, "Profile updated.", null, JOptionPane.OK_OPTION);
                        userNameLabel.setText(userName);
                        break;
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "The code entered is incorrect, please enter the correct code.", "Alert", JOptionPane.WARNING_MESSAGE);
                }               
              }
            }
          }
          catch(NullPointerException ne)
          {
            JOptionPane.showMessageDialog(this, "The code entered is incorrect, please enter the correct code.", "Alert", JOptionPane.WARNING_MESSAGE);
          }
          catch(Exception ex)
          {
            System.out.println(ex);
          }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void userNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyReleased
        // TODO add your handling code here:
        String userName = userNameField.getText();
        if(Pattern.compile("^[a-zA-Z\\s]*$").matcher(userName).matches() && !userName.equals(""))
        {
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(uV.getWidth(), uV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          uV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          uV.setIcon(icon);
        }
    }//GEN-LAST:event_userNameFieldKeyReleased

    private void emailFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyReleased
        // TODO add your handling code here:
        String email = emailField.getText();
        if(Pattern.compile("^[A-Za-z0-9+_.-]+@(.+)$").matcher(email).matches() && !email.equals(""))
        {
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(eV.getWidth(), eV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          eV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          eV.setIcon(icon);
        }
    }//GEN-LAST:event_emailFieldKeyReleased

    private void mobileFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileFieldKeyReleased
        // TODO add your handling code here:
        String mobile = mobileField.getText();
        if(Pattern.compile("^\\d{10}$").matcher(mobile).matches() && !mobile.equals(""))
        {
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(mV.getWidth(), mV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          mV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          mV.setIcon(icon);
        }
    }//GEN-LAST:event_mobileFieldKeyReleased

    private void passFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyReleased
        // TODO add your handling code here:
        String password = new String(passField.getPassword());
        if(Pattern.compile("^(?=.*\\d).{4,15}$").matcher(password).matches() && !password.equals(""))
        {
          ImageIcon icon = new ImageIcon("target/classes/images/accept.png");
          Image img = icon.getImage();                
          Image imgScale = img.getScaledInstance(pV.getWidth(), pV.getHeight(), Image.SCALE_SMOOTH);
          ImageIcon scaledIcon = new ImageIcon(imgScale);  
          pV.setIcon(scaledIcon);
        }
        else
        {
          
          ImageIcon icon = new ImageIcon("target/classes/images/cross.png");
          pV.setIcon(icon);
        }
    }//GEN-LAST:event_passFieldKeyReleased

    private void bookTrainTicketsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookTrainTicketsLabelMouseClicked
        // TODO add your handling code here:
        BookTrainTickets bt = new BookTrainTickets();
        bt.setVisible(true);
    }//GEN-LAST:event_bookTrainTicketsLabelMouseClicked

    private void electricityBillLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electricityBillLabelMouseClicked
        // TODO add your handling code here:
        PayUtilityBill pub = new PayUtilityBill("Electricity");
        pub.setVisible(true);        
    }//GEN-LAST:event_electricityBillLabelMouseClicked

    private void gasBillLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gasBillLabelMouseClicked
        // TODO add your handling code here:
        PayUtilityBill pub = new PayUtilityBill("Gas");
        pub.setVisible(true);  
    }//GEN-LAST:event_gasBillLabelMouseClicked

    private void waterBillLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_waterBillLabelMouseClicked
        // TODO add your handling code here:
        PayUtilityBill pub = new PayUtilityBill("Water");
        pub.setVisible(true);  
    }//GEN-LAST:event_waterBillLabelMouseClicked

    private void mobileRechargeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobileRechargeLabelMouseClicked
        // TODO add your handling code here:
        MobilePayment mp = new MobilePayment();
        mp.setVisible(true);
    }//GEN-LAST:event_mobileRechargeLabelMouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void bookEventTicketsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookEventTicketsLabelMouseClicked
        // TODO add your handling code here:
        BookEventTickets bet = new BookEventTickets();
        bet.setVisible(true);

    }//GEN-LAST:event_bookEventTicketsLabelMouseClicked

    private void bookMovieTicketsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookMovieTicketsLabelMouseClicked
        // TODO add your handling code here:
        BookMovieTickets bmt = new BookMovieTickets();
        bmt.setVisible(true);        
    }//GEN-LAST:event_bookMovieTicketsLabelMouseClicked

    private void spendAnalyticsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spendAnalyticsLabelMouseClicked
        // TODO add your handling code here:       
        SpendAnalytics sa = new SpendAnalytics();        
        sa.setVisible(true);
    }//GEN-LAST:event_spendAnalyticsLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomePage("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel bookBusTicketsLabel;
    private javax.swing.JLabel bookEventTicketsLabel;
    private javax.swing.JLabel bookMovieTicketsLabel;
    private javax.swing.JLabel bookTrainTicketsLabel;
    private javax.swing.JLabel eV;
    private javax.swing.JLabel electricityBillLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel gasBillLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel mV;
    private javax.swing.JTextField mobileField;
    private javax.swing.JLabel mobileRechargeLabel;
    private javax.swing.JLabel moneyToBankLabel;
    private javax.swing.JLabel moneyToOthersWalletLabel;
    private javax.swing.JLabel moneyToWalletLabel;
    private javax.swing.JLabel pV;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel spendAnalyticsLabel;
    private javax.swing.JLabel uV;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField userNameField;
    public static javax.swing.JLabel userNameLabel;
    private javax.swing.JLabel waterBillLabel;
    // End of variables declaration//GEN-END:variables
}
